import { BadgeDollarSign, CheckCircle2, CircleAlert, FileCheck2, Search, Send, WalletCards } from 'lucide-react'
import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { callMethod, ugx } from '../../../../api/frappe'
import { accountTone, FinanceIntro, FinanceMetric, FinancePageState, FinanceStatus, financeDate } from '../FinanceCommon'
import { useFinancePortal } from '../../financePortal'

const createMethod = 'ugandan_university_education.ugandan_university_education.api.create_finance_invoice'
const submitMethod = 'ugandan_university_education.ugandan_university_education.api.submit_finance_invoice'

export function FinanceBillingPage() {
  const { refresh } = useFinancePortal(), [params] = useSearchParams(), [student, setStudent] = useState(params.get('student') ?? ''), [structure, setStructure] = useState(''), [query, setQuery] = useState(params.get('q') ?? ''), [busy, setBusy] = useState(''), [message, setMessage] = useState('')
  return <FinancePageState>{data => {
    const selectedStudent = data.students.find(row => String(row.name) === student)
    const available = data.fee_structures.filter(row => String(row.status) === 'Active' && Number(row.docstatus) === 1 && (!selectedStudent?.academic_programme || String(row.academic_programme) === String(selectedStudent.academic_programme)))
    const rows = data.invoices.filter(row => !query || JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))
    async function createInvoice() { if (!student || !structure) return; setBusy('create'); setMessage(''); try { const name = await callMethod<string>(createMethod, { student, university_fee_structure: structure }); setMessage(`Draft invoice ${name} created for review.`); setStructure(''); refresh() } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'The invoice could not be created.') } finally { setBusy('') } }
    async function submitInvoice(name: string) { if (!window.confirm(`Submit invoice ${name}? Submitted invoices become part of the official student balance.`)) return; setBusy(name); setMessage(''); try { await callMethod(submitMethod, { invoice_name: name }); setMessage(`Invoice ${name} submitted successfully.`); refresh() } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'The invoice could not be submitted.') } finally { setBusy('') } }
    const submitted = data.invoices.filter(row => Number(row.docstatus) === 1), draft = data.invoices.filter(row => Number(row.docstatus) === 0)
    return <section className="student-portal-page"><FinanceIntro icon={BadgeDollarSign} eyebrow="STUDENT BILLING CONTROL" title="Student Invoices" description="Create controlled draft invoices from active fee structures, review them and submit approved charges to student accounts."/>
      <section className="student-portal-metrics"><FinanceMetric icon={WalletCards} label="Submitted invoices" value={submitted.length} detail={ugx(submitted.reduce((sum, row) => sum + Number(row.grand_total ?? 0), 0))} tone="blue"/><FinanceMetric icon={FileCheck2} label="Draft review queue" value={draft.length} detail="not yet charged" tone="gold"/><FinanceMetric icon={CheckCircle2} label="Fully paid" value={submitted.filter(row => Number(row.outstanding_amount ?? 0) === 0).length} detail="settled invoices"/><FinanceMetric icon={CircleAlert} label="Outstanding" value={ugx(submitted.reduce((sum, row) => sum + Number(row.outstanding_amount ?? 0), 0))} detail="balance to collect" tone="danger"/></section>
      <article className="card finance-billing-composer"><div><span className="eyebrow">CREATE CONTROLLED BILL</span><h3>Bill a student from an approved structure</h3><p>The invoice remains a draft until a Finance Officer reviews and submits it.</p></div><label><span>Student account</span><select value={student} onChange={event => { setStudent(event.target.value); setStructure('') }}><option value="">Select student</option>{data.students.map(row => <option key={String(row.name)} value={String(row.name)}>{String(row.student_number ?? row.name)} · {String(row.student_name)}</option>)}</select></label><label><span>Active fee structure</span><select value={structure} onChange={event => setStructure(event.target.value)} disabled={!student}><option value="">Select structure</option>{available.map(row => <option key={String(row.name)} value={String(row.name)}>{String(row.structure_name)} · {ugx(row.total_amount)}</option>)}</select></label><button className="primary-button" disabled={!student || !structure || busy === 'create'} onClick={createInvoice}><BadgeDollarSign size={16}/>{busy === 'create' ? 'Creating…' : 'Create draft invoice'}</button></article>
      {message ? <p className={message.includes('successfully') || message.includes('created') ? 'form-message success' : 'form-message'}>{message}</p> : null}
      <article className="card student-table-card"><div className="receipt-selection-toolbar"><label className="search-input"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search invoice, student, semester or fee structure"/></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Student Account</th><th>Semester / Structure</th><th>Assessed</th><th>Paid</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map(row => { const total = Number(row.grand_total ?? 0), balance = Number(row.outstanding_amount ?? 0); return <tr key={String(row.name)}><td><strong>{String(row.name)}</strong><small>{financeDate(row.posting_date)} · due {financeDate(row.due_date)}</small></td><td>{String(row.student_name ?? row.customer)}<small>{String(row.student_number ?? row.student ?? '')}</small></td><td>{String(row.academic_semester ?? 'Unassigned')}<small>{String(row.university_fee_structure ?? 'Manual invoice')}</small></td><td>{ugx(total)}</td><td>{ugx(total - balance)}</td><td><strong>{ugx(balance)}</strong></td><td><FinanceStatus tone={Number(row.docstatus) === 0 ? 'gold' : accountTone(balance, total)}>{Number(row.docstatus) === 0 ? 'Draft' : String(row.status ?? (balance ? 'Unpaid' : 'Paid'))}</FinanceStatus></td><td>{Number(row.docstatus) === 0 ? <button className="primary-button compact" disabled={busy === String(row.name)} onClick={() => submitInvoice(String(row.name))}><Send size={14}/>{busy === String(row.name) ? 'Submitting…' : 'Submit'}</button> : <FinanceStatus tone="blue">Posted</FinanceStatus>}</td></tr> }) : <tr><td colSpan={8} className="data-table-empty">No invoice matches this search.</td></tr>}</tbody></table></div></article>
    </section>
  }}</FinancePageState>
}
