import { CheckCircle2, CircleAlert, HandCoins, Search, ShieldCheck, XCircle } from 'lucide-react'
import { useState } from 'react'
import { callMethod, ugx } from '../../../../api/frappe'
import { useFinancePortal } from '../../financePortal'
import { FinanceIntro, FinanceMetric, FinancePageState, FinanceStatus } from '../FinanceCommon'

const method = 'ugandan_university_education.ugandan_university_education.api.review_sponsorship_award'
export function FinanceSponsorshipsPage() {
  const { refresh } = useFinancePortal(), [query, setQuery] = useState(''), [busy, setBusy] = useState(''), [message, setMessage] = useState('')
  return <FinancePageState>{data => {
    const rows = data.sponsorships.filter(row => !query || JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))
    async function decide(name: string, decision: string, existing?: unknown) { const reference = decision === 'Cancelled' ? String(existing ?? '') : window.prompt('Enter the sponsorship approval reference:', String(existing ?? '')) ?? ''; if (decision !== 'Cancelled' && !reference) return; setBusy(name); setMessage(''); try { await callMethod(method, { award_name: name, decision, approval_reference: reference }); setMessage(`Sponsorship ${name} moved to ${decision}.`); refresh() } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'The sponsorship could not be updated.') } finally { setBusy('') } }
    const committed = data.sponsorships.reduce((sum, row) => sum + Number(row.coverage_amount ?? 0), 0)
    return <section className="student-portal-page"><FinanceIntro icon={HandCoins} eyebrow="SPONSOR FUNDING CONTROL" title="Student Sponsorships" description="Review sponsor commitments, coverage terms and approval references before activating awards on student accounts."/>
      <section className="student-portal-metrics"><FinanceMetric icon={HandCoins} label="Awards" value={data.sponsorships.length} detail="all sponsorship records" tone="blue"/><FinanceMetric icon={CheckCircle2} label="Active" value={data.sponsorships.filter(row => String(row.status) === 'Active').length} detail="current awards"/><FinanceMetric icon={CircleAlert} label="Awaiting action" value={data.sponsorships.filter(row => ['Draft', 'Approved'].includes(String(row.status))).length} detail="review queue" tone="gold"/><FinanceMetric icon={ShieldCheck} label="Fixed commitments" value={ugx(committed)} detail="recorded coverage amounts" tone="violet"/></section>
      {message ? <p className={message.includes('moved') ? 'form-message success' : 'form-message'}>{message}</p> : null}
      <article className="card student-table-card"><div className="receipt-selection-toolbar"><label className="search-input"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search student, sponsor, programme, year or reference"/></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Student</th><th>Sponsor</th><th>Academic Coverage</th><th>Award</th><th>Approval Reference</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map(row => <tr key={String(row.name)}><td><strong>{String(row.student_name ?? row.student)}</strong><small>{String(row.student_number ?? row.student)}</small></td><td>{String(row.sponsor)}</td><td>{String(row.academic_programme ?? 'All programme fees')}<small>{String(row.academic_year)}</small></td><td><strong>{String(row.coverage_type)}</strong><small>{String(row.coverage_type) === 'Percentage' ? `${Number(row.coverage_percentage ?? 0)}%` : String(row.coverage_type) === 'Full Tuition' ? 'Full tuition' : ugx(row.coverage_amount)}</small></td><td>{String(row.approval_reference ?? '—')}</td><td><FinanceStatus tone={String(row.status) === 'Active' ? 'green' : ['Draft', 'Approved'].includes(String(row.status)) ? 'gold' : 'danger'}>{String(row.status)}</FinanceStatus></td><td><div className="table-row-actions">{String(row.status) === 'Draft' ? <button disabled={busy === String(row.name)} onClick={() => decide(String(row.name), 'Approved', row.approval_reference)}><CheckCircle2 size={14}/>Approve</button> : null}{String(row.status) === 'Approved' ? <button disabled={busy === String(row.name)} onClick={() => decide(String(row.name), 'Active', row.approval_reference)}><ShieldCheck size={14}/>Activate</button> : null}{!['Cancelled', 'Exhausted'].includes(String(row.status)) ? <button disabled={busy === String(row.name)} onClick={() => decide(String(row.name), 'Cancelled', row.approval_reference)}><XCircle size={14}/>Cancel</button> : null}</div></td></tr>) : <tr><td colSpan={7} className="data-table-empty">No sponsorship matches this search.</td></tr>}</tbody></table></div></article>
    </section>
  }}</FinancePageState>
}
