import { Award, BookOpenCheck, CalendarDays, FileBadge2, ReceiptText, ShieldCheck, WalletCards } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { ugx } from '../../../../api/frappe'
import { StudentMetric, StudentPageState, StudentStatus } from '../StudentCommon'

export function StudentDashboardPage(){
  const navigate=useNavigate()
  return <StudentPageState>{data=>{const outstanding=data.invoices.reduce((sum,row)=>sum+Number(row.outstanding_amount??0),0),paid=data.invoices.reduce((sum,row)=>sum+Number(row.grand_total??0)-Number(row.outstanding_amount??0),0),published=data.results.length,current=data.enrolments.find(row=>String(row.status)==='Active')??data.enrolments[0];return <section className="student-portal-page">
    <section className="student-welcome card"><div><span className="eyebrow">WELCOME TO MY AWU</span><h1>Hello, {String(data.student.first_name??data.student.student_name??'Student')}</h1><p>Follow your registration, classes, fees, results, transcript and clearance from one secure student workspace.</p><div className="hero-action-row"><button className="primary-button light" onClick={()=>navigate('/student/courses')}><BookOpenCheck size={16}/>My courses</button><button className="secondary-button translucent" onClick={()=>navigate('/student/finance')}><ReceiptText size={16}/>Fees and receipts</button></div></div><aside><span>Student number</span><strong>{String(data.student.student_number??data.student.name)}</strong><small>{String(current?.academic_programme??'Programme awaiting assignment')}</small><StudentStatus>{String(data.student.status??'Active')}</StudentStatus></aside></section>
    <section className="student-portal-metrics"><StudentMetric icon={BookOpenCheck} label="Registered courses" value={data.course_registrations.length} detail="courses on your academic record" tone="blue"/><StudentMetric icon={CalendarDays} label="Semester registrations" value={data.semester_registrations.length} detail="completed registration periods"/><StudentMetric icon={WalletCards} label="Balance to pay" value={ugx(outstanding)} detail={`${ugx(paid)} paid to date`} tone={outstanding?'gold':'green'}/><StudentMetric icon={Award} label="Published results" value={published} detail="approved course results" tone="violet"/></section>
    <section className="student-dashboard-grid"><article className="card student-service-card"><div className="section-heading"><div><span className="eyebrow">CURRENT ACADEMIC RECORD</span><h3>Programme and registration</h3></div><CalendarDays size={22}/></div><dl className="student-definition-list"><div><dt>Programme</dt><dd>{String(current?.academic_programme??'—')}</dd></div><div><dt>Academic year</dt><dd>{String(current?.academic_year??'—')}</dd></div><div><dt>Cohort</dt><dd>{String(current?.student_cohort??'—')}</dd></div><div><dt>Status</dt><dd>{String(current?.status??'—')}</dd></div></dl><button className="inline-link" onClick={()=>navigate('/student/registration')}>View registration details</button></article><article className="card student-service-card"><div className="section-heading"><div><span className="eyebrow">STUDENT SERVICES</span><h3>Document readiness</h3></div><ShieldCheck size={22}/></div><div className="student-service-list"><button onClick={()=>navigate('/student/results')}><Award size={18}/><span><strong>Results</strong><small>{published} published records</small></span></button><button onClick={()=>navigate('/student/transcript')}><FileBadge2 size={18}/><span><strong>Transcript</strong><small>{data.transcripts.length} approved document(s)</small></span></button><button onClick={()=>navigate('/student/clearance')}><ShieldCheck size={18}/><span><strong>Clearance</strong><small>{data.clearance.length} clearance case(s)</small></span></button></div></article></section>
  </section>}}</StudentPageState>
}
