import { useState, type ReactNode } from 'react'
import { Bell, LogOut, MoreHorizontal, UserCircle2, X } from 'lucide-react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { authApi, type UniversitySession } from '../../../api/frappe'
import { lecturerNavigation } from '../roleConfig'

function active(path:string,location:string){return location===path||(path!=='/lecturer'&&location.startsWith(path))}
export function LecturerShell({session,onLogout,children}:{session:UniversitySession;onLogout:()=>void;children:ReactNode}){const location=useLocation(),navigate=useNavigate(),[moreOpen,setMoreOpen]=useState(false),current=lecturerNavigation.find(item=>active(item.path,location.pathname))??lecturerNavigation[0],mobileItems=lecturerNavigation.filter(item=>['/lecturer','/lecturer/offerings','/lecturer/attendance','/lecturer/marks'].includes(item.path));async function logout(){await authApi.logout().catch(()=>undefined);onLogout();navigate('/login',{replace:true})}return <div className="app-shell role-shell role-shell-lecturer">
  <div className="desktop-sidebar-cap"><div className="desktop-sidebar-cap-mark"><img src="/awu-logo.png" alt="Ankole Western University"/></div></div>
  <header className="topbar card desktop-topbar"><div className="student-topbar-context"><span className="eyebrow">AWU TEACHING PORTAL</span><strong>{current.label}</strong></div><div className="topbar-actions"><button className="topbar-icon-button" aria-label="Notifications"><Bell size={18}/></button><button className="topbar-user-chip" onClick={()=>navigate('/lecturer/profile')}><span className="topbar-user-avatar">{session.initials}</span><span className="topbar-user-copy"><strong>{session.fullName}</strong><small>Lecturer</small></span></button></div></header>
  <aside className="sidebar desktop-sidebar"><div className="sidebar-heading"><img src="/awu-logo.png" alt=""/><span><strong>AWU</strong><small>Teaching Portal</small></span></div><nav className="nav-list" aria-label="Lecturer navigation">{lecturerNavigation.map(item=><NavLink key={item.path} to={item.path} end={item.path==='/lecturer'} className={()=>active(item.path,location.pathname)?'nav-item nav-item-active':'nav-item'}><item.icon size={18}/><span>{item.label}</span></NavLink>)}</nav><div className="sidebar-actions"><button className="sidebar-icon-button" onClick={()=>navigate('/lecturer/profile')}><UserCircle2 size={17}/></button><button className="sidebar-icon-button" onClick={logout}><LogOut size={17}/></button></div></aside>
  <header className="mobile-header card"><div className="mobile-header-brand"><div className="brand-mark"><img src="/awu-logo.png" alt="Ankole Western University"/></div><div><p>AWU Teaching Portal</p><strong>{current.label}</strong></div></div><button className="mobile-icon-button"><Bell size={18}/></button></header>
  <section className="workspace"><main className="page-stack">{children}</main></section>
  <nav className="mobile-bottom-nav card" aria-label="Lecturer mobile navigation">{mobileItems.map(item=><NavLink key={item.path} to={item.path} end={item.path==='/lecturer'} className={()=>active(item.path,location.pathname)?'bottom-nav-item bottom-nav-item-active':'bottom-nav-item'}><item.icon size={18}/><span>{item.label.replace('Course ','').replace('Enter ','')}</span></NavLink>)}<button className={moreOpen?'bottom-nav-item bottom-nav-item-active':'bottom-nav-item'} onClick={()=>setMoreOpen(value=>!value)}><MoreHorizontal size={18}/><span>More</span></button></nav>
  {moreOpen?<div className="mobile-more-overlay mobile-more-overlay-open"><button className="mobile-more-backdrop" onClick={()=>setMoreOpen(false)}/><section className="mobile-more-sheet card"><div className="mobile-more-sheet-header"><div><span className="eyebrow">TEACHING PORTAL</span><h2>More lecturer services</h2></div><button className="mobile-icon-button" onClick={()=>setMoreOpen(false)}><X size={18}/></button></div><div className="mobile-more-list">{lecturerNavigation.filter(item=>!mobileItems.includes(item)).map(item=><NavLink key={item.path} to={item.path} className="mobile-more-item" onClick={()=>setMoreOpen(false)}><item.icon size={18}/><span>{item.label}</span></NavLink>)}<button className="mobile-more-item ghost-danger" onClick={logout}><LogOut size={18}/><span>Sign out</span></button></div></section></div>:null}
 </div>}
