import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Activity, BookOpen, CheckCircle2, ClipboardCheck, Edit3, FileText, GraduationCap, Link2, Plus, ShieldCheck, UserPlus, Users, WalletCards, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { callMethod, createDocument, fetchDocument, fetchList, updateDocument, type FrappeRow } from '../../../../api/frappe'
import type { RecordView } from './RecordsPage'

export type FormField = { name: string; label: string; required?: boolean; type?: 'text'|'email'|'date'|'number'|'select'; options?: string[]; link?: string }

export const formSchemas: Partial<Record<RecordView, FormField[]>> = {
  students: [{name:'first_name',label:'First name',required:true},{name:'last_name',label:'Last name',required:true},{name:'student_email_id',label:'Email',type:'email',required:true},{name:'student_number',label:'Student number'},{name:'gender',label:'Gender',type:'select',options:['Male','Female','Other']},{name:'status',label:'Status',type:'select',options:['Active','On Leave','Completed','Withdrawn'],required:true}],
  applications: [{name:'applicant_name',label:'Applicant name',required:true},{name:'applicant_email',label:'Applicant email',type:'email',required:true},{name:'academic_programme',label:'Programme',required:true,link:'Academic Programme'},{name:'programme_curriculum',label:'Curriculum',link:'Programme Curriculum'},{name:'academic_year',label:'Academic year',required:true,link:'Academic Year'},{name:'application_date',label:'Application date',type:'date'},{name:'status',label:'Status',type:'select',options:['Draft','Submitted','Under Review','Accepted','Rejected']}],
  programmes: [{name:'programme_code',label:'Programme code',required:true},{name:'programme_name',label:'Programme name',required:true},{name:'award_type',label:'Award type',required:true},{name:'academic_unit',label:'Academic unit',required:true,link:'Academic Unit'},{name:'duration_years',label:'Duration (years)',type:'number'},{name:'status',label:'Status',type:'select',options:['Active','Inactive','Archived']}],
  courses: [{name:'course_code',label:'Course code',required:true},{name:'course_name',label:'Course name',required:true},{name:'academic_unit',label:'Academic unit',required:true,link:'Academic Unit'},{name:'credit_units',label:'Credit units',type:'number',required:true},{name:'study_level',label:'Study level'},{name:'status',label:'Status',type:'select',options:['Active','Inactive','Archived']}],
  units: [{name:'unit_code',label:'Unit code',required:true},{name:'unit_name',label:'Unit name',required:true},{name:'unit_type',label:'Unit type',type:'select',options:['Faculty','School','Department']},{name:'parent_academic_unit',label:'Parent unit',link:'Academic Unit'},{name:'head_member',label:'Head member',link:'University Member'},{name:'status',label:'Status',type:'select',options:['Active','Inactive','Archived']}],
  curricula: [{name:'curriculum_name',label:'Curriculum name',required:true},{name:'academic_programme',label:'Programme',required:true,link:'Academic Programme'},{name:'academic_year',label:'Academic year',required:true,link:'Academic Year'},{name:'effective_from',label:'Effective from',type:'date'},{name:'status',label:'Status',type:'select',options:['Draft','Active','Archived']}],
  cohorts: [{name:'cohort_code',label:'Cohort code',required:true},{name:'cohort_name',label:'Cohort name',required:true},{name:'academic_programme',label:'Programme',required:true,link:'Academic Programme'},{name:'programme_curriculum',label:'Curriculum',link:'Programme Curriculum'},{name:'academic_year',label:'Academic year',required:true,link:'Academic Year'},{name:'campus',label:'Campus'},{name:'status',label:'Status',type:'select',options:['Active','Completed','Archived']}],
  offerings: [{name:'course',label:'Course',required:true,link:'Course'},{name:'academic_semester',label:'Academic semester',required:true,link:'Academic Semester'},{name:'student_cohort',label:'Cohort',link:'Student Cohort'},{name:'programme_curriculum',label:'Programme curriculum',link:'Programme Curriculum'},{name:'offering_type',label:'Offering type',type:'select',options:['Core','Elective','Retake','Supplementary']},{name:'capacity',label:'Capacity',type:'number'},{name:'grading_scheme',label:'Grading scheme',link:'Grading Scheme'},{name:'lecturer',label:'Lecturer / University Member',link:'University Member'},{name:'teaching_role',label:'Teaching role',type:'select',options:['Lecturer','Coordinator','Moderator']},{name:'status',label:'Status',type:'select',options:['Planned','Open','Closed','Cancelled']}],
}

type AuditEntry = { at: string; action: string; reason?: string }
const auditKey = (entity:string,name:string)=>`awu-admin-audit:${entity}:${name}`
function readAudit(entity:string,name:string):AuditEntry[]{try{return JSON.parse(localStorage.getItem(auditKey(entity,name))??'[]')}catch{return[]}}
function recordAudit(entity:string,name:string,action:string,reason?:string){const rows=[{at:new Date().toISOString(),action,reason},...readAudit(entity,name)].slice(0,50);localStorage.setItem(auditKey(entity,name),JSON.stringify(rows));void callMethod('ugandan_university_education.ugandan_university_education.api.log_university_audit_event',{entity_type:entity,entity_name:name,action,reason:reason??'',metadata:JSON.stringify({source:'university-admin-frontend'})}).catch(()=>undefined)}

export function supportsNativeForm(view:RecordView){return Boolean(formSchemas[view])}

export function LegacyRecordFormModal({view,doctype,record,defaults,onClose,onSaved}:{view:RecordView;doctype:string;record?:FrappeRow|null;defaults?:FrappeRow;onClose:()=>void;onSaved:(saved:FrappeRow)=>void|Promise<void>}){
  const fields=formSchemas[view]??[], [values,setValues]=useState<FrappeRow>({...defaults,...record}), [error,setError]=useState(''), [saving,setSaving]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();const missing=fields.find(field=>field.required&&!String(values[field.name]??'').trim());if(missing)return setError(`${missing.label} is required.`);setSaving(true);setError('');try{const name=String(record?.name??'');const payload=Object.fromEntries(fields.map(field=>[field.name,values[field.name]]).filter(([,value])=>value!==''&&value!==undefined));if(view==='offerings'){const lecturer=payload.lecturer;delete payload.lecturer;delete payload.teaching_role;if(lecturer)payload.lecturers=[{lecturer,is_primary:1,teaching_role:values.teaching_role||'Lecturer'}]}const saved=name?await updateDocument(doctype,name,payload):await createDocument(doctype,payload);if(!name&&view==='students'&&defaults?.student_cohort&&saved.name)await callMethod('ugandan_university_education.ugandan_university_education.api.assign_student_to_cohort',{student:String(saved.name),student_cohort:String(defaults.student_cohort)});recordAudit(doctype,String(saved.name??name),name?'updated':'created');await onSaved(saved);onClose()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save record.')}finally{setSaving(false)}}
  return <div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={onClose} aria-label="Close form"/><form className="admin-record-form card" onSubmit={submit} role="dialog" aria-modal="true"><header><div><span className="eyebrow">{record?'EDIT':'CREATE'} {doctype}</span><h2>{record?String(record.name):`New ${doctype}`}</h2></div><button type="button" onClick={onClose} aria-label="Close"><X size={18}/></button></header><div className="admin-form-grid">{fields.map(field=><label key={field.name}><span>{field.label}{field.required?' *':''}</span>{field.type==='select'?<select value={String(values[field.name]??'')} onChange={event=>setValues(current=>({...current,[field.name]:event.target.value}))}><option value="">Select…</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input type={field.type??'text'} value={String(values[field.name]??'')} onChange={event=>setValues(current=>({...current,[field.name]:field.type==='number'?Number(event.target.value):event.target.value}))}/>}</label>)}</div>{error?<p className="form-message">{error}</p>:null}<footer><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving…':'Save record'}</button></footer></form></div>
}

export function GuardianContactModal({student,onClose,onSaved}:{student:string;onClose:()=>void;onSaved:()=>void}){
  const [values,setValues]=useState({first_name:'',last_name:'',email:'',phone:''}),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();if(!values.first_name.trim())return setError('First name is required.');setSaving(true);setError('');try{await createDocument('Contact',{first_name:values.first_name,last_name:values.last_name,email_ids:values.email?[{email_id:values.email,is_primary:1}]:[],phone_nos:values.phone?[{phone:values.phone,is_primary_phone:1}]:[],links:[{link_doctype:'Student',link_name:student}]});recordAudit('Student',student,'Guardian/contact added');onSaved();onClose()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save this guardian/contact.')}finally{setSaving(false)}}
  return <div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={onClose} aria-label="Close guardian form"/><form className="admin-record-form card compact-related-modal" onSubmit={submit} role="dialog" aria-modal="true"><header><div><span className="eyebrow">RELATED RECORD</span><h2>Add guardian/contact</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="admin-form-grid">{(['first_name','last_name','email','phone'] as const).map(field=><label key={field}><span>{field.replace('_',' ')}{field==='first_name'?' *':''}</span><input type={field==='email'?'email':'text'} value={values[field]} onChange={event=>setValues({...values,[field]:event.target.value})}/></label>)}</div>{error?<p className="form-message">{error}</p>:null}<footer><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving…':'Save contact'}</button></footer></form></div>
}

type Workflow = { label:string; method:string; args:(row:FrappeRow,reason:string)=>Record<string,string>; needsReason?:boolean; confirm:string }
function workflows(view:RecordView,row:FrappeRow):Workflow[]{
  if(view==='applications')return [
    {label:'Move to review',method:'ugandan_university_education.ugandan_university_education.api.review_registrar_application',args:(r,reason)=>({application_name:String(r.name),decision:'Under Review',comments:reason}),confirm:'Move this application to review?'},
    {label:'Admit & create student',method:'ugandan_university_education.ugandan_university_education.api.admit_application',args:r=>({application_name:String(r.name)}),confirm:'Admit this applicant and create their student record?'},
    {label:'Reject',method:'ugandan_university_education.ugandan_university_education.api.review_registrar_application',args:(r,reason)=>({application_name:String(r.name),decision:'Rejected',comments:reason}),needsReason:true,confirm:'Reject this application?'}]
  if(view==='approval-batches')return [{label:'Publish approved batch',method:'ugandan_university_education.ugandan_university_education.api.publish_registrar_result_batch',args:r=>({batch_name:String(r.name)}),confirm:'Publish all approved results in this batch?'}]
  if(view==='transcript-register')return [{label:'Issue transcript',method:'ugandan_university_education.ugandan_university_education.api.issue_registrar_transcript',args:r=>({transcript_name:String(r.name)}),confirm:'Issue this certified transcript?'},{label:'Revoke transcript',method:'ugandan_university_education.ugandan_university_education.api.revoke_registrar_transcript',args:(r,reason)=>({transcript_name:String(r.name),reason}),needsReason:true,confirm:'Revoke this issued transcript?'}]
  if(view==='clearance'||view==='readiness')return [{label:'Review clearance',method:'ugandan_university_education.ugandan_university_education.api.review_registrar_clearance',args:r=>({clearance_name:String(r.name)}),confirm:'Refresh and review this clearance case?'}]
  if(view==='invoices')return [{label:'Submit invoice',method:'ugandan_university_education.ugandan_university_education.api.submit_finance_invoice',args:r=>({invoice_name:String(r.name)}),confirm:'Submit this draft student invoice?'}]
  if(view==='sponsorships')return [{label:'Approve award',method:'ugandan_university_education.ugandan_university_education.api.review_sponsorship_award',args:(r,reason)=>({award_name:String(r.name),decision:'Approved',approval_reference:reason}),needsReason:true,confirm:'Approve this sponsorship award?'}]
  return []
}

const studentRelations=[{tab:'Enrolment',doctype:'Student Programme Enrolment',icon:GraduationCap},{tab:'Finance',doctype:'Sales Invoice',icon:WalletCards},{tab:'Results',doctype:'Student Course Result',icon:ClipboardCheck},{tab:'Documents',doctype:'Academic Transcript',icon:FileText}]

export function AdminRecordDrawer({view,doctype,columns,row,onClose,onEdit}:{view:RecordView;doctype:string;columns:Array<{field:string;label:string}>;row:FrappeRow;onClose:()=>void;onEdit?:()=>void}){
  const navigate=useNavigate(), name=String(row.name??''), [record,setRecord]=useState(row), [tab,setTab]=useState('Profile'), [related,setRelated]=useState<FrappeRow[]>([]), [busy,setBusy]=useState(''), [message,setMessage]=useState(''), [reason,setReason]=useState(''), [audit,setAudit]=useState(()=>readAudit(doctype,name))
  const availableTabs=useMemo(()=>view==='students'?['Profile',...studentRelations.map(item=>item.tab),'Activity']:view==='programmes'?['Profile','Cohorts','Offerings','Students','Activity']:view==='payments'?['Profile','Allocations','Activity']:['Profile','Activity'],[view])
  useEffect(()=>{fetchDocument(doctype,name).then(setRecord).catch(()=>undefined)},[doctype,name])
  useEffect(()=>{const local=[{at:new Date().toISOString(),action:'viewed'},...readAudit(doctype,name)].slice(0,50);localStorage.setItem(auditKey(doctype,name),JSON.stringify(local));setAudit(local);callMethod('ugandan_university_education.ugandan_university_education.api.log_university_audit_event',{entity_type:doctype,entity_name:name,action:'viewed',metadata:JSON.stringify({source:'record-drawer'})}).then(()=>callMethod<Array<{action:string;reason?:string;event_time:string}>>('ugandan_university_education.ugandan_university_education.api.get_university_audit_timeline',{entity_type:doctype,entity_name:name,limit:'50'})).then(rows=>setAudit(rows.map(item=>({at:item.event_time,action:item.action,reason:item.reason})))).catch(()=>setAudit(local))},[doctype,name])
  useEffect(()=>{setRelated([]);if(view==='payments'&&tab==='Allocations'){setRelated(Array.isArray(record.references)?record.references as FrappeRow[]:[])}else if(view==='students'){const relation=studentRelations.find(item=>item.tab===tab);if(relation)fetchList(relation.doctype,['name','student','status','academic_programme','academic_year','grand_total','outstanding_amount','course','grade','verification_number'],[['student','=',name]],50).then(setRelated).catch(()=>setRelated([]))}else if(view==='programmes'&&tab!=='Profile'&&tab!=='Activity'){const map={Cohorts:['Student Cohort','academic_programme'],Offerings:['Course Offering','academic_programme'],Students:['Student Programme Enrolment','academic_programme']} as const;const relation=map[tab as keyof typeof map];if(relation)fetchList(relation[0],['name','student','course','student_cohort','academic_year','status'],[[relation[1],'=',String(record.name)]],50).then(setRelated).catch(()=>setRelated([]))}},[tab,view,name,record.name,record.references])
  async function run(flow:Workflow){if(flow.needsReason&&!reason.trim())return setMessage('A reason or reference is required.');if(!window.confirm(flow.confirm))return;setBusy(flow.label);setMessage('');try{await callMethod(flow.method,flow.args(record,reason));recordAudit(doctype,name,flow.label,reason);setAudit(readAudit(doctype,name));setMessage(`${flow.label} completed.`);setRecord(await fetchDocument(doctype,name));setReason('')}catch(cause){setMessage(cause instanceof Error?cause.message:'Workflow action failed.')}finally{setBusy('')}}
  const flows=workflows(view,record)
  return <div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={onClose} aria-label="Close record drawer"/><aside className="record-drawer admin-record-drawer" role="dialog" aria-modal="true"><header><div><span className="eyebrow">NATIVE {doctype}</span><h2>{name}</h2></div><button onClick={onClose} aria-label="Close"><X size={18}/></button></header><nav className="drawer-tabs">{availableTabs.map(label=><button className={tab===label?'is-active':''} onClick={()=>setTab(label)} key={label}>{label}</button>)}</nav>{tab==='Profile'?<><div className="drawer-context-actions">{onEdit?<button onClick={onEdit}><Edit3 size={15}/>Edit</button>:null}{view==='students'?<button onClick={()=>navigate(`/students/profile/${encodeURIComponent(name)}`)}><Users size={15}/>Full profile</button>:null}{view==='cohorts'?<button onClick={()=>navigate(`/students?create=student&cohort=${encodeURIComponent(name)}`)}><UserPlus size={15}/>Add student</button>:null}{view==='offerings'?<><button onClick={()=>navigate(`/registration/timetables?q=${encodeURIComponent(name)}`)}><BookOpen size={15}/>Timetable</button><button onClick={onEdit}><Link2 size={15}/>Assign lecturer</button></>:null}</div><dl>{columns.map(column=><div key={column.field}><dt>{column.label}</dt><dd>{String(record[column.field]??'—')}</dd></div>)}</dl>{flows.length?<section className="workflow-panel"><h3><ShieldCheck size={17}/>Governed actions</h3><textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Reason, comments, or approval reference"/><div>{flows.map(flow=><button className="primary-button compact" disabled={Boolean(busy)} onClick={()=>run(flow)} key={flow.label}><CheckCircle2 size={14}/>{busy===flow.label?'Working…':flow.label}</button>)}</div></section>:null}{message?<p className={`form-message ${message.endsWith('completed.')?'success':''}`}>{message}</p>:null}</>:tab==='Activity'?<section className="audit-timeline"><h3><Activity size={17}/>Sensitive action history</h3>{audit.length?audit.map((item,index)=><div key={`${item.at}-${index}`}><CheckCircle2 size={15}/><span><strong>{item.action}</strong><small>{new Date(item.at).toLocaleString()}{item.reason?` · ${item.reason}`:''}</small></span></div>):<p>No actions recorded in this browser session.</p>}</section>:<section className="drawer-related"><h3>{tab}</h3>{related.length?related.map(item=><button key={String(item.name)} onClick={()=>navigate(`?record=${encodeURIComponent(String(item.name))}`)}><span><strong>{String(item.name)}</strong><small>{String(item.status??item.academic_year??item.course??'Related record')}</small></span><span className="status-pill tone-green">Open</span></button>):<p>No related records found.</p>}</section>}</aside></div>
}

export function CreateRecordButton({label,onClick}:{label:string;onClick:()=>void}){return <button className="primary-button compact" onClick={onClick}><Plus size={15}/>{label}</button>}
