import { ArrowLeft, Check, CheckCircle2, LoaderCircle, Plus, Search, Sparkles, Table2, Trash2, X } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { callMethod, createDocument, updateDocument, type FrappeRow } from '../../../../api/frappe'
import { formSchemas, type FormField } from './AdminLifecycle'
import type { RecordView } from './RecordsPage'

type Step={name:string;fields:FormField[]}
type LinkedDraft={id:string;doctype:string;parentId:string;parentField:string;values:FrappeRow}
type Toast={id:number;tone:'success'|'error';title:string;detail:string}
const api='ugandan_university_education.ugandan_university_education.api'
const linkedSchemas:Record<string,FormField[]>={
  'Academic Programme':formSchemas.programmes??[], 'Programme Curriculum':formSchemas.curricula??[],
  'Academic Unit':formSchemas.units??[], Course:formSchemas.courses??[], 'Student Cohort':formSchemas.cohorts??[],
  'Academic Year':[{name:'year_name',label:'Academic year',required:true},{name:'year_start_date',label:'Start date',type:'date',required:true},{name:'year_end_date',label:'End date',type:'date',required:true},{name:'status',label:'Status',type:'select',options:['Planned','Open','Closed','Archived'],required:true}],
  'Academic Semester':[{name:'semester_name',label:'Semester name',required:true},{name:'academic_year',label:'Academic year',required:true,link:'Academic Year'},{name:'semester_number',label:'Semester number',type:'number',required:true},{name:'start_date',label:'Start date',type:'date',required:true},{name:'end_date',label:'End date',type:'date',required:true},{name:'status',label:'Status',type:'select',options:['Planned','Open','Closed'],required:true}],
  'University Member':[{name:'member_number',label:'Member number',required:true},{name:'full_name',label:'Full name',required:true},{name:'member_type',label:'Member type',type:'select',options:['Student','Lecturer','Staff','External'],required:true},{name:'status',label:'Status',type:'select',options:['Active','Inactive','Suspended'],required:true}],
  'Grading Scheme':[{name:'scheme_name',label:'Scheme name',required:true},{name:'description',label:'Description'},{name:'status',label:'Status',type:'select',options:['Draft','Active','Retired'],required:true}],
}
const stepNames=['Identity & context','Academic relationships','Status & review']
function stepsFor(fields:FormField[]):Step[]{const size=Math.max(1,Math.ceil(fields.length/3));return Array.from({length:Math.ceil(fields.length/size)},(_,index)=>({name:stepNames[index]??`Additional details ${index+1}`,fields:fields.slice(index*size,(index+1)*size)}))}
function complete(fields:FormField[],values:FrappeRow){return fields.filter(field=>field.required).every(field=>String(values[field.name]??'').trim())}
function payloadFor(view:RecordView,fields:FormField[],values:FrappeRow){const payload=Object.fromEntries(fields.map(field=>[field.name,values[field.name]]).filter(([,value])=>value!==''&&value!==undefined));if(view==='offerings'){const lecturer=payload.lecturer;delete payload.lecturer;delete payload.teaching_role;if(lecturer)payload.lecturers=[{lecturer,is_primary:1,teaching_role:values.teaching_role||'Lecturer'}]}return payload}

export function GuidedRecordFormModal({view,doctype,record,defaults,onClose,onSaved}:{view:RecordView;doctype:string;record?:FrappeRow|null;defaults?:FrappeRow;onClose:()=>void;onSaved:(saved:FrappeRow)=>void|Promise<void>}){
  const fields=formSchemas[view]??[],steps=stepsFor(fields)
  const [values,setValues]=useState<FrappeRow>({...defaults,...record}),[active,setActive]=useState('root'),[step,setStep]=useState(0)
  const [linked,setLinked]=useState<LinkedDraft[]>([]),[completed,setCompleted]=useState<string[]>([]),[staged,setStaged]=useState<FrappeRow[]>([])
  const [error,setError]=useState(''),[saving,setSaving]=useState(false),[toasts,setToasts]=useState<Toast[]>([])
  function toast(tone:Toast['tone'],title:string,detail:string){const id=Date.now();setToasts(current=>[...current,{id,tone,title,detail}]);window.setTimeout(()=>setToasts(current=>current.filter(item=>item.id!==id)),4200)}
  function openLinked(target:string,parentField:string,parentId:string){const found=linked.find(item=>item.doctype===target&&item.parentField===parentField&&item.parentId===parentId);if(found)return setActive(found.id);const id=`linked-${Date.now()}-${linked.length}`;setLinked(current=>[...current,{id,doctype:target,parentId,parentField,values:{}}]);setActive(id)}
  function updateLinked(id:string,field:string,value:unknown){setLinked(current=>current.map(item=>item.id===id?{...item,values:{...item.values,[field]:value}}:item))}
  function closeLinked(id:string){const item=linked.find(row=>row.id===id);setLinked(current=>current.filter(row=>row.id!==id));setActive(item?.parentId??'root')}
  async function saveLinked(item:LinkedDraft){const itemFields=linkedSchemas[item.doctype]??[],missing=itemFields.find(field=>field.required&&!String(item.values[field.name]??'').trim());if(missing)return toast('error','Linked form incomplete',`${missing.label} is required.`);setSaving(true);try{const saved=await createDocument(item.doctype,Object.fromEntries(itemFields.map(field=>[field.name,item.values[field.name]]).filter(([,value])=>value!==''&&value!==undefined))),name=String(saved.name);if(item.parentId==='root')setValues(current=>({...current,[item.parentField]:name}));else updateLinked(item.parentId,item.parentField,name);setCompleted(current=>[...current,`${item.doctype}: ${name}`]);toast('success',`${item.doctype} created`,`${name} was selected in the previous form.`);closeLinked(item.id)}catch(cause){toast('error',`Unable to create ${item.doctype}`,cause instanceof Error?cause.message:'ERPNext validation failed.')}finally{setSaving(false)}}
  function stage(){const missing=fields.find(field=>field.required&&!String(values[field.name]??'').trim());if(missing)return toast('error','Cannot stage record',`${missing.label} is required.`);setStaged(current=>[...current,payloadFor(view,fields,values)]);setValues({...defaults});setStep(0);toast('success','Record staged',`${staged.length+1} validated row${staged.length?'s are':' is'} ready.`)}
  async function createStaged(){if(!staged.length)return;setSaving(true);try{const result=await callMethod<{count:number}>(`${api}.create_university_native_records`,{doctype,rows:JSON.stringify(staged)});setStaged([]);toast('success',`${result.count} records created`,'The complete staged set passed validation and was committed together.');await onSaved({name:'__batch__'})}catch(cause){toast('error','Batch not created',cause instanceof Error?cause.message:'No staged rows were committed.')}finally{setSaving(false)}}
  async function submit(event:FormEvent){event.preventDefault();const missing=fields.find(field=>field.required&&!String(values[field.name]??'').trim());if(missing){setStep(Math.max(0,steps.findIndex(item=>item.fields.includes(missing))));setActive('root');return setError(`${missing.label} is required.`)}setSaving(true);setError('');try{const name=String(record?.name??''),saved=name?await updateDocument(doctype,name,payloadFor(view,fields,values)):await createDocument(doctype,payloadFor(view,fields,values));if(!name&&view==='students'&&defaults?.student_cohort&&saved.name)await callMethod(`${api}.assign_student_to_cohort`,{student:String(saved.name),student_cohort:String(defaults.student_cohort)});void callMethod(`${api}.log_university_audit_event`,{entity_type:doctype,entity_name:String(saved.name??name),action:name?'updated':'created',metadata:JSON.stringify({source:'guided-form-workspace'})}).catch(()=>undefined);toast('success',`${doctype} ${name?'updated':'created'}`,String(saved.name??name));await onSaved(saved);onClose()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save record.')}finally{setSaving(false)}}
  const ready=steps.every(item=>complete(item.fields,values))&&!linked.length
  return <div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={onClose} aria-label="Close form"/><form className="admin-record-form university-form-workspace card" onSubmit={submit} role="dialog" aria-modal="true"><header><div><span className="eyebrow">{record?'EDIT':'CREATE'} {doctype}</span><h2>{record?String(record.name):`New ${doctype}`}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><Progress steps={steps} values={values} linked={linked} completed={completed} active={active} step={step} ready={ready} chooseRoot={index=>{setActive('root');setStep(index)}} chooseLinked={setActive}/><nav className="university-form-tabs"><button type="button" className={active==='root'?'active':''} onClick={()=>setActive('root')}><Table2 size={14}/>{doctype}</button>{linked.map(item=><button type="button" className={active===item.id?'active':''} onClick={()=>setActive(item.id)} key={item.id}><Plus size={14}/>{item.doctype}<X size={12} onClick={event=>{event.stopPropagation();closeLinked(item.id)}}/></button>)}</nav>{active==='root'?<><div className="admin-form-grid">{steps[step]?.fields.map(field=><Field field={field} value={values[field.name]} contextId="root" onQuick={openLinked} onChange={value=>setValues(current=>({...current,[field.name]:value}))} key={field.name}/>)}</div><div className="university-step-controls"><button type="button" disabled={step===0} onClick={()=>setStep(current=>current-1)}><ArrowLeft size={14}/>Previous</button><span>Step {step+1} of {steps.length}</span><button type="button" disabled={step===steps.length-1} onClick={()=>setStep(current=>current+1)}>Next<ArrowLeft className="next-arrow" size={14}/></button></div>{!record?<Staging rows={staged} saving={saving} onStage={stage} onRemove={index=>setStaged(current=>current.filter((_,rowIndex)=>rowIndex!==index))} onCreate={()=>void createStaged()}/>:null}</>:linked.map(item=>active===item.id?<LinkedForm item={item} saving={saving} onBack={()=>setActive(item.parentId)} onChange={(field,value)=>updateLinked(item.id,field,value)} onQuick={openLinked} onSave={()=>void saveLinked(item)} key={item.id}/>:null)}{error?<p className="form-message">{error}</p>:null}<footer><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving||active!=='root'}>{saving?'Saving...':record?'Save updates':'Create record'}</button></footer></form><ToastStack rows={toasts}/></div>
}

function Progress({steps,values,linked,completed,active,step,ready,chooseRoot,chooseLinked}:{steps:Step[];values:FrappeRow;linked:LinkedDraft[];completed:string[];active:string;step:number;ready:boolean;chooseRoot:(index:number)=>void;chooseLinked:(id:string)=>void}){let count=0;return <section className="university-form-progress"><header><div><span className="eyebrow">GUIDED WORKFLOW</span><strong>{steps.length+linked.length+completed.length+1} steps across this form stream</strong></div><small>{steps.filter(item=>complete(item.fields,values)).length+completed.length} complete</small></header><div>{steps.map((item,index)=>{const done=complete(item.fields,values);count++;return <button type="button" className={`${done?'done':''} ${active==='root'&&step===index?'active':''}`} onClick={()=>chooseRoot(index)} key={item.name}><b>{done?<Check size={14}/>:count}</b><span>{item.name}<small>{done?'Complete':'Information pending'}</small></span></button>})}{completed.map(item=><div className="done" key={item}><b><Check size={14}/></b><span>{item}<small>Linked form created</small></span></div>)}{linked.map(item=><button type="button" className={active===item.id?'active':''} onClick={()=>chooseLinked(item.id)} key={item.id}><b>{++count}</b><span>{item.doctype}<small>Linked form in progress</small></span></button>)}<div className={ready?'done':''}><b>{ready?<Check size={14}/>:++count}</b><span>Review & submit<small>{ready?'Ready':'Complete earlier steps'}</small></span></div></div></section>}
function Field({field,value,contextId,onQuick,onChange}:{field:FormField;value:unknown;contextId:string;onQuick:(target:string,field:string,parentId:string)=>void;onChange:(value:unknown)=>void}){return <label><span>{field.label}{field.required?' *':''}</span>{field.link?<LinkField target={field.link} fieldname={field.name} contextId={contextId} value={String(value??'')} onQuick={onQuick} onChange={onChange}/>:field.type==='select'?<select value={String(value??'')} onChange={event=>onChange(event.target.value)}><option value="">Select...</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input type={field.type??'text'} value={String(value??'')} onChange={event=>onChange(field.type==='number'?Number(event.target.value):event.target.value)}/>}</label>}
function LinkField({target,fieldname,contextId,value,onQuick,onChange}:{target:string;fieldname:string;contextId:string;value:string;onQuick:(target:string,field:string,parentId:string)=>void;onChange:(value:unknown)=>void}){const[options,setOptions]=useState<Array<{value:string;label:string}>>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false);useEffect(()=>{const timer=window.setTimeout(()=>{setLoading(true);callMethod<Array<{value:string;label:string}>>(`${api}.search_university_link_options`,{doctype:target,txt:value,limit:'30'}).then(setOptions).catch(()=>setOptions([])).finally(()=>setLoading(false))},180);return()=>window.clearTimeout(timer)},[target,value]);return <div className="university-link-field"><div><Search size={14}/><input value={value} autoComplete="off" onFocus={()=>setOpen(true)} onBlur={()=>window.setTimeout(()=>setOpen(false),160)} onChange={event=>{onChange(event.target.value);setOpen(true)}}/>{loading?<LoaderCircle className="spin" size={14}/>:null}</div>{open?<section>{options.length?options.map(item=><button type="button" onMouseDown={event=>event.preventDefault()} onClick={()=>{onChange(item.value);setOpen(false)}} key={item.value}><span><strong>{item.label}</strong><small>{item.value}</small></span><Check size={14}/></button>):<p>No matching {target} found.</p>}{linkedSchemas[target]?<button type="button" className="create-link" onMouseDown={event=>event.preventDefault()} onClick={()=>onQuick(target,fieldname,contextId)}><Plus size={14}/>Create new {target} in another form tab</button>:null}</section>:null}</div>}
function LinkedForm({item,saving,onBack,onChange,onQuick,onSave}:{item:LinkedDraft;saving:boolean;onBack:()=>void;onChange:(field:string,value:unknown)=>void;onQuick:(target:string,field:string,parentId:string)=>void;onSave:()=>void}){const fields=linkedSchemas[item.doctype]??[];return <section className="university-linked-form"><header><div><span className="eyebrow">INLINE LINKED FORM</span><h3>Create {item.doctype}</h3><p>The previous form and temporary table remain saved.</p></div><button type="button" onClick={onBack}><ArrowLeft size={14}/>Back</button></header><div className="admin-form-grid">{fields.map(field=><Field field={field} value={item.values[field.name]} contextId={item.id} onQuick={onQuick} onChange={value=>onChange(field.name,value)} key={field.name}/>)}</div><footer><button type="button" onClick={onBack}>Keep draft & go back</button><button type="button" className="primary-button" disabled={saving} onClick={onSave}><Sparkles size={14}/>{saving?'Creating...':`Create & select ${item.doctype}`}</button></footer></section>}
function Staging({rows,saving,onStage,onRemove,onCreate}:{rows:FrappeRow[];saving:boolean;onStage:()=>void;onRemove:(index:number)=>void;onCreate:()=>void}){return <section className="university-staging"><header><div><strong><Table2 size={15}/>Multi-record staging</strong><small>Add each completed form to this temporary table, then submit all at once.</small></div><button type="button" onClick={onStage}><Plus size={14}/>Add form to table</button></header>{rows.length?<><table><thead><tr><th>#</th><th>Preview</th><th/></tr></thead><tbody>{rows.map((row,index)=><tr key={index}><td>{index+1}</td><td>{Object.values(row).filter(value=>value!==''&&value!=null&&!Array.isArray(value)).slice(0,4).join(' · ')}</td><td><button type="button" onClick={()=>onRemove(index)}><Trash2 size={14}/></button></td></tr>)}</tbody></table><footer><span>{rows.length} ready</span><button type="button" className="primary-button" disabled={saving} onClick={onCreate}><CheckCircle2 size={14}/>Validate & create {rows.length}</button></footer></>:<p>No temporary rows yet. The form above remains active.</p>}</section>}
function ToastStack({rows}:{rows:Toast[]}){return <div className="university-toast-stack" aria-live="polite">{rows.map(item=><article className={item.tone} key={item.id}>{item.tone==='success'?<Check size={17}/>:<X size={17}/>}<div><strong>{item.title}</strong><span>{item.detail}</span></div></article>)}</div>}
