import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { Check, ChevronDown, ChevronLeft, ChevronRight, Columns3, Download, Eye, Filter, MoreHorizontal, Save, Search, SlidersHorizontal, Upload, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { callMethod, createDocument, type FrappeRow, type ListFilter, type ListPageQuery } from '../api/frappe'
import { ShellStatePanel } from './ShellStatePanel'

export type WorkbenchColumn = { field: string; label: string; render?: (value: unknown, row: FrappeRow) => ReactNode }
export type WorkbenchAction = { label: string; icon?: typeof Eye; onSelect: (row: FrappeRow) => void }
export type DataWorkbenchSchema = {
  entity: string
  title: string
  description: string
  columns: WorkbenchColumn[]
  searchFields: string[]
  defaultSort?: string
  allowImport?: boolean
  quickFilters?: Array<{ label: string; field: string; value: string }>
  filterFields?: Array<{ field: string; label: string }>
}

type PageResult = { rows: FrappeRow[]; page: number; pageSize: number; hasNext: boolean }
type Props = {
  schema: DataWorkbenchSchema
  loadPage: (query: ListPageQuery, signal?: AbortSignal) => Promise<PageResult>
  actions?: (row: FrappeRow) => WorkbenchAction[]
  primaryAction?: ReactNode
  renderDrawer?: (row: FrappeRow, close: () => void) => ReactNode
  importFields?: string[]
  importRows?: (rows: FrappeRow[]) => Promise<void>
}
const pageSizes = [25, 50, 100, 2000] as const
const operators: ListFilter['operator'][] = ['=','!=','like','in','>','>=','<','<=']

function csvCell(value: unknown) { const text = String(value ?? ''); return `"${text.replace(/"/g, '""')}"` }
function saveCsv(filename: string, columns: WorkbenchColumn[], rows: FrappeRow[]) { const csv = [columns.map(column => csvCell(column.label)).join(','), ...rows.map(row => columns.map(column => csvCell(row[column.field])).join(','))].join('\r\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); window.dispatchEvent(new CustomEvent('awu:workbench-export',{detail:{filename,count:rows.length}})) }
function safeFilters(value: string | null): ListFilter[] { try { const parsed = JSON.parse(value ?? '[]'); return Array.isArray(parsed) ? parsed.filter(item => item?.field && operators.includes(item.operator)) : [] } catch { return [] } }

export function DataWorkbench({ schema, loadPage, actions, primaryAction, renderDrawer, importFields, importRows }: Props) {
  const [params, setParams] = useSearchParams()
  const [draftSearch, setDraftSearch] = useState(params.get('q') ?? '')
  const [rows, setRows] = useState<FrappeRow[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [hasNext, setHasNext] = useState(false), [selected, setSelected] = useState<Set<string>>(new Set()), [drawerRow, setDrawerRow] = useState<FrappeRow | null>(null)
  const [filterOpen, setFilterOpen] = useState(false), [columnOpen, setColumnOpen] = useState(false), [importOpen, setImportOpen] = useState(false), [exporting, setExporting] = useState(false)
  const [importFile, setImportFile] = useState<File | null>(null), [importMessage,setImportMessage]=useState(''), [importing,setImporting]=useState(false), requestRef = useRef(0)
  const page = Math.max(1, Number(params.get('page') ?? 1)), pageSize = pageSizes.includes(Number(params.get('pageSize')) as never) ? Number(params.get('pageSize')) as typeof pageSizes[number] : 50
  const filters = useMemo(() => safeFilters(params.get('filters')), [params]), sortField = params.get('sort') ?? schema.defaultSort ?? 'modified', sortOrder = params.get('order') === 'asc' ? 'asc' : 'desc'
  const density = params.get('density') ?? 'comfortable', storedColumns = params.get('columns')?.split(',').filter(Boolean)
  const filterOptions = useMemo(() => [...schema.columns.map(({field,label})=>({field,label})),...(schema.filterFields??[])].filter((item,index,all)=>all.findIndex(candidate=>candidate.field===item.field)===index),[schema.columns,schema.filterFields])
  const visibleColumns = useMemo(() => { const allowed = new Set(schema.columns.map(column => column.field)); const selectedFields = storedColumns?.filter(field => allowed.has(field)); const fields = selectedFields?.length ? selectedFields : schema.columns.map(column => column.field); return fields.map(field => schema.columns.find(column => column.field === field)!).filter(Boolean) }, [schema.columns, storedColumns])

  function updateParams(values: Record<string, string | number | null>, replace = false) { const next = new URLSearchParams(params); Object.entries(values).forEach(([key, value]) => value === null || value === '' ? next.delete(key) : next.set(key, String(value))); setParams(next, { replace }) }
  useEffect(() => { const timer = window.setTimeout(() => updateParams({ q: draftSearch || null, page: 1 }, true), 350); return () => window.clearTimeout(timer) }, [draftSearch])
  useEffect(() => {
    const controller = new AbortController(), requestId = ++requestRef.current
    setLoading(true); setError('')
    loadPage({ search: params.get('q') ?? '', searchFields: schema.searchFields, filters, page, pageSize, sortField, sortOrder }, controller.signal)
      .then(result => { if (requestId !== requestRef.current) return; setRows(result.rows); setHasNext(result.hasNext); setSelected(new Set()) })
      .catch(cause => { if (cause?.name !== 'AbortError' && requestId === requestRef.current) setError(cause instanceof Error ? cause.message : 'Unable to load records.') })
      .finally(() => { if (requestId === requestRef.current) setLoading(false) })
    return () => controller.abort()
  }, [schema.entity, params.get('q'), params.get('filters'), params.get('refresh'), page, pageSize, sortField, sortOrder])
  useEffect(()=>{const requested=params.get('record');if(requested){const match=rows.find(row=>String(row.name)===requested);if(match)setDrawerRow(match)}},[rows,params.get('record')])
  useEffect(()=>{const audit=(event:Event)=>{const detail=(event as CustomEvent<{count:number}>).detail;void callMethod('ugandan_university_education.ugandan_university_education.api.log_university_audit_event',{entity_type:schema.entity,entity_name:'__aggregate__',action:'exported',metadata:JSON.stringify({source:'data-workbench',selection_count:detail?.count??0})}).catch(()=>undefined)};window.addEventListener('awu:workbench-export',audit);return()=>window.removeEventListener('awu:workbench-export',audit)},[schema.entity])

  const rowKey = (row: FrappeRow, index = 0) => String(row.name ?? `${schema.entity}-${index}`)
  const allSelected = rows.length > 0 && rows.every((row, index) => selected.has(rowKey(row, index)))
  function toggleAll() { setSelected(allSelected ? new Set() : new Set(rows.map(rowKey))) }
  function toggleRow(key: string) { setSelected(current => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next }) }
  function applyQuickFilter(field: string, value: string) { const next = filters.filter(filter => filter.field !== field); if (!filters.some(filter => filter.field === field && filter.value === value)) next.push({ field, operator: '=', value }); updateParams({ filters: next.length ? JSON.stringify(next) : null, page: 1 }) }
  function addFilter() { updateParams({ filters: JSON.stringify([...filters, { field: filterOptions[0].field, operator: '=', value: '' }]), page: 1 }) }
  function updateFilter(index: number, patch: Partial<ListFilter>) { const next = filters.map((filter, itemIndex) => itemIndex === index ? { ...filter, ...patch } : filter); updateParams({ filters: JSON.stringify(next), page: 1 }, true) }
  function removeFilter(index: number) { const next = filters.filter((_, itemIndex) => itemIndex !== index); updateParams({ filters: next.length ? JSON.stringify(next) : null, page: 1 }) }
  function toggleColumn(field: string) { const fields = visibleColumns.map(column => column.field); const next = fields.includes(field) ? fields.filter(item => item !== field) : [...fields, field]; if (next.length) updateParams({ columns: next.join(',') }) }
  function moveColumn(field: string, direction: -1 | 1) { const fields = visibleColumns.map(column => column.field), index = fields.indexOf(field), target = index + direction; if (target < 0 || target >= fields.length) return; [fields[index], fields[target]] = [fields[target], fields[index]]; updateParams({ columns: fields.join(',') }) }
  function saveView() { const name = window.prompt('Saved view name'); if (!name) return; const key = `awu-workbench:${schema.entity}`; const views = JSON.parse(localStorage.getItem(key) ?? '{}'); views[name] = Object.fromEntries(params.entries()); localStorage.setItem(key, JSON.stringify(views)) }
  function loadSavedView() { const key = `awu-workbench:${schema.entity}`; const views = JSON.parse(localStorage.getItem(key) ?? '{}'); const names = Object.keys(views); if (!names.length) return window.alert('No saved views yet.'); const name = window.prompt(`Saved views:\n${names.join('\n')}\n\nEnter a view name`); if (name && views[name]) setParams(new URLSearchParams(views[name])) }
  async function exportAll() { setExporting(true); try { const collected: FrappeRow[] = []; for (let exportPage = 1; exportPage <= 200; exportPage += 1) { const result = await loadPage({ search: params.get('q') ?? '', searchFields: schema.searchFields, filters, page: exportPage, pageSize: 50, sortField, sortOrder }); collected.push(...result.rows); if (!result.hasNext || collected.length >= 10000) break } saveCsv(`${schema.entity}-filtered.csv`, visibleColumns, collected) } finally { setExporting(false) } }
  function approvedImportFields(){if(importFields?.length)return importFields;if(schema.entity==='Student')return ['first_name','last_name','student_email_id','student_number','gender','status'];if(schema.entity==='University Application')return ['applicant_name','applicant_email','academic_programme','programme_curriculum','academic_year','application_date','status'];return schema.columns.map(column=>column.field)}
  function downloadTemplate(){const fields=approvedImportFields();saveCsv(`${schema.entity}-approved-template.csv`,fields.map(field=>({field,label:field})),[])}
  async function validateAndImport(){if(!importFile)return;setImporting(true);setImportMessage('');try{const text=await importFile.text(),lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),headers=(lines.shift()??'').split(',').map(value=>value.trim().replace(/^"|"$/g,''));const approved=approvedImportFields(),unknown=headers.filter(field=>!approved.includes(field));if(unknown.length)throw new Error(`Unsupported columns: ${unknown.join(', ')}`);const rows=lines.map(line=>{const values=line.split(',').map(value=>value.trim().replace(/^"|"$/g,'').replace(/""/g,'"'));return Object.fromEntries(headers.map((header,index)=>[header,values[index]??'']))});if(!rows.length)throw new Error('The CSV contains no data rows.');if(importRows)await importRows(rows);else for(const row of rows)await createDocument(schema.entity,row);void callMethod('ugandan_university_education.ugandan_university_education.api.log_university_audit_event',{entity_type:schema.entity,entity_name:'__aggregate__',action:'imported',metadata:JSON.stringify({source:'data-workbench',selection_count:rows.length})}).catch(()=>undefined);setImportMessage(`${rows.length} rows imported successfully.`);updateParams({refresh:Date.now()})}catch(cause){setImportMessage(cause instanceof Error?cause.message:'Unable to validate this file.')}finally{setImporting(false)}}

  return <article className={`card data-workbench density-${density}`} aria-busy={loading}>
    <header className="workbench-heading"><div><span className="eyebrow">NATIVE DATA WORKBENCH</span><h2>{schema.title}</h2><p>{schema.description}</p></div><div className="workbench-heading-actions">{primaryAction}<button type="button" onClick={saveView}><Save size={15}/>Save view</button><button type="button" onClick={loadSavedView}>Saved views<ChevronDown size={14}/></button></div></header>
    <div className="workbench-toolbar"><label className="search-input"><Search size={16}/><input value={draftSearch} onChange={event => setDraftSearch(event.target.value)} placeholder={`Search ${schema.title.toLowerCase()}`} aria-label={`Search ${schema.title}`} /></label><button type="button" className={filterOpen ? 'is-active' : ''} onClick={() => setFilterOpen(value => !value)}><Filter size={15}/>Filters{filters.length ? <b>{filters.length}</b> : null}</button><button type="button" onClick={() => setColumnOpen(value => !value)}><Columns3 size={15}/>Columns</button><select aria-label="Table density" value={density} onChange={event => updateParams({ density: event.target.value })}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="spacious">Spacious</option></select><div className="workbench-export"><button type="button" onClick={() => saveCsv(`${schema.entity}-page-${page}.csv`, visibleColumns, rows)}><Download size={15}/>Page</button><button type="button" disabled={!selected.size} onClick={() => saveCsv(`${schema.entity}-selected.csv`, visibleColumns, rows.filter((row, index) => selected.has(rowKey(row,index))))}>Selected</button><button type="button" disabled={exporting} onClick={exportAll}>{exporting ? 'Preparing…' : 'All filtered'}</button></div><button type="button" disabled={!schema.allowImport} title={schema.allowImport ? 'Import records' : 'Import is not permitted for this entity'} onClick={() => setImportOpen(true)}><Upload size={15}/>Import</button></div>
    {schema.quickFilters?.length ? <div className="workbench-quick-filters" aria-label="Quick filters">{schema.quickFilters.map(filter => { const on = filters.some(item => item.field === filter.field && item.value === filter.value); return <button key={`${filter.field}-${filter.value}`} className={on ? 'is-active' : ''} onClick={() => applyQuickFilter(filter.field, filter.value)}>{on ? <Check size={13}/> : null}{filter.label}</button> })}</div> : null}
    {filterOpen ? <section className="workbench-filter-builder"><header><strong>Advanced filters</strong><button type="button" onClick={addFilter}>Add filter</button></header>{filters.map((filter,index) => <div className="workbench-filter-row" key={index}><select aria-label="Filter field" value={filter.field} onChange={event => updateFilter(index,{field:event.target.value})}>{filterOptions.map(column=><option key={column.field} value={column.field}>{column.label}</option>)}</select><select aria-label="Filter operator" value={filter.operator} onChange={event => updateFilter(index,{operator:event.target.value as ListFilter['operator']})}>{operators.map(operator=><option key={operator}>{operator}</option>)}</select><input aria-label="Filter value" value={filter.value} onChange={event => updateFilter(index,{value:event.target.value})}/><button type="button" onClick={()=>removeFilter(index)} aria-label="Remove filter"><X size={15}/></button></div>)}</section> : null}
    {columnOpen ? <section className="workbench-column-manager"><strong>Visible columns and order</strong>{schema.columns.map(column => <div key={column.field}><label><input type="checkbox" checked={visibleColumns.some(item=>item.field===column.field)} onChange={()=>toggleColumn(column.field)}/>{column.label}</label><span><button onClick={()=>moveColumn(column.field,-1)} aria-label={`Move ${column.label} left`}>←</button><button onClick={()=>moveColumn(column.field,1)} aria-label={`Move ${column.label} right`}>→</button></span></div>)}</section> : null}
    {selected.size ? <div className="workbench-bulk-bar"><strong>{selected.size} selected</strong><button onClick={() => saveCsv(`${schema.entity}-selected.csv`, visibleColumns, rows.filter((row,index)=>selected.has(rowKey(row,index))))}><Download size={15}/>Export selection</button><button onClick={()=>setSelected(new Set())}>Clear</button></div> : null}
    {error ? <ShellStatePanel variant="error" message={error} action={<button className="primary-button" onClick={()=>updateParams({refresh:Date.now()})}>Retry</button>}/> : <div className="table-wrap"><table className="data-table workbench-table"><caption className="sr-only">{schema.title}; page {page}</caption><thead><tr><th className="selection-column"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Select all rows on this page"/></th>{visibleColumns.map(column => <th key={column.field} scope="col"><button className="sortable-heading" onClick={()=>updateParams({sort:column.field,order:sortField===column.field&&sortOrder==='asc'?'desc':'asc',page:1})}>{column.label}{sortField===column.field?<span>{sortOrder==='asc'?'↑':'↓'}</span>:null}</button></th>)}<th scope="col">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={visibleColumns.length+2}><ShellStatePanel variant="loading" title="Loading records"/></td></tr> : rows.length ? rows.map((row,index)=>{const key=rowKey(row,index);return <tr key={key}><td className="selection-column"><input type="checkbox" checked={selected.has(key)} onChange={()=>toggleRow(key)} aria-label={`Select ${key}`}/></td>{visibleColumns.map((column,columnIndex)=><td key={column.field}>{column.render?column.render(row[column.field],row):columnIndex===0?<strong>{String(row[column.field]??row.name??'—')}</strong>:String(row[column.field]??'—')}</td>)}<td><div className="table-row-actions"><button onClick={()=>setDrawerRow(row)} aria-label={`View ${key}`} title="View record"><Eye size={14}/>View</button>{(actions?.(row)??[]).slice(0,2).map(action=><button key={action.label} onClick={()=>action.onSelect(row)} title={action.label}>{action.icon?<action.icon size={14}/>:<MoreHorizontal size={14}/>}<span>{action.label}</span></button>)}</div></td></tr>}):<tr><td colSpan={visibleColumns.length+2}><ShellStatePanel variant="empty"/></td></tr>}</tbody></table></div>}
    <footer className="workbench-pagination"><span>Page <strong>{page}</strong> · {rows.length} rows</span><label>Rows per page <select value={pageSize} onChange={event=>updateParams({pageSize:event.target.value,page:1})}>{pageSizes.map(size=><option key={size}>{size}</option>)}</select></label><div><button disabled={page<=1||loading} onClick={()=>updateParams({page:page-1})}><ChevronLeft size={15}/>Previous</button><button disabled={!hasNext||loading} onClick={()=>updateParams({page:page+1})}>Next<ChevronRight size={15}/></button></div></footer>
    {drawerRow ? renderDrawer?.(drawerRow,()=>setDrawerRow(null)) ?? <div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={()=>setDrawerRow(null)} aria-label="Close record drawer"/><aside className="record-drawer" role="dialog" aria-modal="true" aria-label={`${schema.entity} details`}><header><div><span className="eyebrow">{schema.entity}</span><h2>{String(drawerRow.name??schema.title)}</h2></div><button onClick={()=>setDrawerRow(null)} aria-label="Close drawer"><X size={18}/></button></header><dl>{schema.columns.map(column=><div key={column.field}><dt>{column.label}</dt><dd>{String(drawerRow[column.field]??'—')}</dd></div>)}</dl></aside></div>:null}
    {importOpen ? <div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={()=>setImportOpen(false)} aria-label="Close import wizard"/><section className="import-wizard card" role="dialog" aria-modal="true" aria-label={`Import ${schema.entity}`}><header><div><span className="eyebrow">IMPORT WIZARD</span><h2>Import {schema.title}</h2></div><button onClick={()=>setImportOpen(false)} aria-label="Close import wizard"><X size={18}/></button></header><p>Use the approved template. Files are limited to 10 MiB and column validation runs before records are committed.</p><button type="button" onClick={downloadTemplate}><Download size={15}/>Download approved template</button><input type="file" accept=".csv,text/csv" onChange={event=>{setImportFile(event.target.files?.[0]??null);setImportMessage('')}}/>{importFile?<div className="import-file-summary"><strong>{importFile.name}</strong><span>{Math.ceil(importFile.size/1024)} KiB</span>{importFile.size<=10*1024*1024?<span className="status-pill tone-green">Ready to validate</span>:<span className="status-pill">File too large</span>}</div>:null}{importMessage?<p className="form-message">{importMessage}</p>:null}<footer><button onClick={()=>setImportOpen(false)}>Cancel</button><button className="primary-button" disabled={!importFile||importFile.size>10*1024*1024||importing} onClick={validateAndImport}>{importing?'Working…':'Validate and import'}</button></footer></section></div>:null}
  </article>
}
