import { useEffect, useMemo, useRef, useState } from 'react'
import { CircleOff, Command, CornerDownLeft, Search } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { auditDiscovery, searchFacultyScope, searchRegistrarScope, searchStudentJourney, searchUniversity, type DiscoveryResult } from '../api/universityDiscovery'
import type { PortalRole } from '../roles/admin/roleConfig'

const groupOrder: DiscoveryResult['group'][] = ['Navigation','Records','Tree','Actions','Help']

export function GlobalSearch({ role = 'staff', mobile = false, onNavigate }: { role?: PortalRole; mobile?: boolean; onNavigate?: () => void }) {
  const navigate=useNavigate(),inputRef=useRef<HTMLInputElement>(null),returnFocusRef=useRef<HTMLElement|null>(null),requestRef=useRef(0)
  const [query,setQuery]=useState(''),[results,setResults]=useState<DiscoveryResult[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[highlighted,setHighlighted]=useState(0)
  useEffect(()=>{function shortcut(event:KeyboardEvent){if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();returnFocusRef.current=document.activeElement as HTMLElement;setOpen(true);window.setTimeout(()=>inputRef.current?.focus(),0)}}window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[])
  useEffect(()=>{if(query.trim().length<2){setResults([]);return}const controller=new AbortController(),id=++requestRef.current,timer=window.setTimeout(()=>{setLoading(true);const request=role==='student'?searchStudentJourney(query.trim()):role==='faculty-head'?searchFacultyScope(query.trim()):role==='registrar'?searchRegistrarScope(query.trim()):searchUniversity(query.trim(),role,controller.signal);request.then(rows=>{if(id===requestRef.current){setResults(rows);setHighlighted(0);auditDiscovery('search',{queryLength:query.trim().length})}}).catch(cause=>{if(cause?.name!=='AbortError'&&id===requestRef.current)setResults([])}).finally(()=>{if(id===requestRef.current)setLoading(false)})},280);return()=>{window.clearTimeout(timer);controller.abort()}},[query,role])
  const grouped=useMemo(()=>groupOrder.map(group=>[group,results.filter(result=>result.group===group)] as const).filter(([,rows])=>rows.length),[results])
  function close(restore=false){setOpen(false);if(restore)window.setTimeout(()=>returnFocusRef.current?.focus(),0)}
  function select(result:DiscoveryResult){auditDiscovery('search_select',{queryLength:query.trim().length,kind:result.kind,route:result.route});const [pathname,rawSearch]=result.route.split('?'),params=new URLSearchParams(rawSearch??'');params.set('searchResult',result.id);if(result.treePath)params.set('tree',result.treePath);navigate({pathname,search:`?${params}`});setQuery('');close(true);onNavigate?.()}
  function keyDown(event:React.KeyboardEvent<HTMLInputElement>){if(event.key==='ArrowDown'){event.preventDefault();setHighlighted(value=>Math.min(results.length-1,value+1))}if(event.key==='ArrowUp'){event.preventDefault();setHighlighted(value=>Math.max(0,value-1))}if(event.key==='Escape'){event.preventDefault();close(true)}if(event.key==='Enter'&&results[highlighted]){event.preventDefault();select(results[highlighted])}}
  return <div className={`topbar-search-block${mobile?' mobile-search-block':''}`} onBlur={()=>window.setTimeout(()=>setOpen(false),150)}>
    <label className="topbar-search" aria-label="Search the University"><Search size={18}/><input ref={inputRef} value={query} placeholder="Search student, cohort, offering, invoice, result or transcript" onFocus={event=>{returnFocusRef.current=event.currentTarget;setOpen(true)}} onChange={event=>{setQuery(event.target.value);setOpen(true)}} onKeyDown={keyDown} aria-controls="university-search-results" aria-expanded={open}/>{loading?<span className="search-loading">Searching…</span>:<kbd><Command size={12}/>K</kbd>}</label>
    {open&&query.trim().length>=2?<div id="university-search-results" className="global-search-results card" role="listbox" aria-label="University search results"><div className="global-search-header"><strong>University search</strong><span>{results.length} permitted result(s)</span></div>{grouped.length?<div className="global-search-groups">{grouped.map(([group,rows])=><section key={group} className="global-search-group"><h3>{group}</h3><div>{rows.map(result=>{const index=results.indexOf(result),active=index===highlighted;return <button key={result.id} role="option" aria-selected={active} className={active?'global-discovery-result is-active':'global-discovery-result'} onMouseEnter={()=>setHighlighted(index)} onMouseDown={event=>event.preventDefault()} onClick={()=>select(result)}><span><strong>{result.title}</strong><small>{result.kind} · {result.detail}</small></span><CornerDownLeft size={15}/></button>})}</div></section>)}</div>:!loading?<div className="empty-state"><CircleOff size={16}/><span>No permitted University records match this search.</span></div>:null}</div>:null}
  </div>
}
