import { useEffect, useRef, useState } from 'react'
import { ChevronRight, FolderTree, GraduationCap, History, Pin, PinOff, Plus, School, Search, UserRound, X } from 'lucide-react'
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import type { PortalRole } from '../roles/admin/roleConfig'
import { auditDiscovery, explorerRoots, loadExplorerChildren, type ExplorerNode } from '../api/universityDiscovery'

function iconFor(node:ExplorerNode){if(node.kind==='root')return School;if(node.entity==='Student'||node.entity==='Enrolment')return UserRound;if(node.entity==='Programme'||node.entity==='Course'||node.entity==='Offering')return GraduationCap;return FolderTree}
function readNodes(key:string):ExplorerNode[]{try{return JSON.parse(localStorage.getItem(key)??'[]')}catch{return[]}}

export function UniversityExplorer({role,open,onClose,returnFocus}:{role:PortalRole;open:boolean;onClose:()=>void;returnFocus?:React.RefObject<HTMLElement|null>}){
 const navigate=useNavigate(),location=useLocation(),[params,setParams]=useSearchParams(),[children,setChildren]=useState<Record<string,ExplorerNode[]>>({}),[expanded,setExpanded]=useState<Set<string>>(new Set()),[loading,setLoading]=useState<Set<string>>(new Set()),[pins,setPins]=useState<ExplorerNode[]>(()=>readNodes('awu-explorer-pins')),[recent,setRecent]=useState<ExplorerNode[]>(()=>readNodes('awu-explorer-recent')),panelRef=useRef<HTMLElement>(null)
 const roots=explorerRoots(role),selectedPath=params.get('tree')??''
 useEffect(()=>{if(open){auditDiscovery('tree_open');window.setTimeout(()=>panelRef.current?.focus(),0)}} ,[open])
 function close(){onClose();window.setTimeout(()=>returnFocus?.current?.focus(),0)}
 async function toggle(node:ExplorerNode){if(!node.expandable)return select(node);setExpanded(current=>{const next=new Set(current);next.has(node.id)?next.delete(node.id):next.add(node.id);return next});if(children[node.id])return;setLoading(current=>new Set(current).add(node.id));try{const rows=await loadExplorerChildren(node,role);setChildren(current=>({...current,[node.id]:rows}))}finally{setLoading(current=>{const next=new Set(current);next.delete(node.id);return next})}}
 function select(node:ExplorerNode){auditDiscovery('tree_select',{kind:node.entity??node.kind,route:node.route});const nextRecent=[node,...recent.filter(item=>item.id!==node.id)].slice(0,8);setRecent(nextRecent);localStorage.setItem('awu-explorer-recent',JSON.stringify(nextRecent));if(node.route){const target=new URLSearchParams(node.route.split('?')[1]??'');target.set('tree',`university/${node.entity??node.kind}/${node.recordId??node.id}`);navigate({pathname:node.route.split('?')[0],search:`?${target}`});close()}else{const next=new URLSearchParams(params);next.set('tree',node.id);setParams(next)}}
 function pin(node:ExplorerNode){const next=pins.some(item=>item.id===node.id)?pins.filter(item=>item.id!==node.id):[node,...pins].slice(0,12);setPins(next);localStorage.setItem('awu-explorer-pins',JSON.stringify(next))}
 function NodeRow({node,depth=0}:{node:ExplorerNode;depth?:number}){const Icon=iconFor(node),isExpanded=expanded.has(node.id),isPinned=pins.some(item=>item.id===node.id),isSelected=selectedPath.includes(node.recordId??node.id);return <li role="treeitem" aria-expanded={node.expandable?isExpanded:undefined} aria-selected={isSelected}><div className={isSelected?'explorer-row explorer-row-selected':'explorer-row'} style={{paddingLeft:12+depth*18}}><button className="explorer-node-main" onClick={()=>toggle(node)} onDoubleClick={()=>select(node)} onKeyDown={event=>{if(event.key==='ArrowRight'&&node.expandable&&!isExpanded){event.preventDefault();toggle(node)}if(event.key==='ArrowLeft'&&node.expandable&&isExpanded){event.preventDefault();toggle(node)}if(event.key==='Enter'&&!node.expandable){event.preventDefault();select(node)}}}><ChevronRight className={isExpanded?'explorer-chevron is-open':'explorer-chevron'} size={14}/><Icon size={16}/><span><strong>{node.label}</strong><small>{node.metadata}</small></span></button><div className="explorer-node-actions"><button onClick={()=>pin(node)} title={isPinned?'Unpin':'Pin'} aria-label={`${isPinned?'Unpin':'Pin'} ${node.label}`}>{isPinned?<PinOff size={14}/>:<Pin size={14}/>}</button>{node.route?<button onClick={()=>select(node)} title="Open" aria-label={`Open ${node.label}`}><Search size={14}/></button>:null}{node.createRoute?<button onClick={()=>navigate(node.createRoute!)} title="Add child" aria-label={`Add under ${node.label}`}><Plus size={14}/></button>:null}</div></div>{node.expandable&&isExpanded?<ul role="group">{loading.has(node.id)?<li className="explorer-loading">Loading…</li>:(children[node.id]??[]).map(child=><NodeRow key={child.id} node={child} depth={depth+1}/>)}</ul>:null}</li>}
 if(!open)return null
 return <div className="explorer-layer"><button className="explorer-backdrop" onClick={close} aria-label="Close University explorer"/><aside ref={panelRef} tabIndex={-1} className="university-explorer" role="dialog" aria-modal="true" aria-label="University tree explorer" onKeyDown={event=>{if(event.key==='Escape')close()}}><header><div><span className="eyebrow">UNIVERSITY EXPLORER</span><h2><FolderTree size={20}/>Browse the institution</h2></div><button onClick={close} aria-label="Close explorer"><X size={18}/></button></header>{pins.length?<section className="explorer-shortcuts"><h3><Pin size={14}/>Pinned</h3><div>{pins.map(node=><button key={node.id} onClick={()=>select(node)}>{node.label}</button>)}</div></section>:null}{recent.length?<section className="explorer-shortcuts"><h3><History size={14}/>Recent</h3><div>{recent.slice(0,5).map(node=><button key={node.id} onClick={()=>select(node)}>{node.label}</button>)}</div></section>:null}<nav className="explorer-tree-scroll" aria-label="University hierarchy"><ul className="explorer-tree" role="tree">{roots.map(node=><NodeRow key={node.id} node={node}/>)}</ul></nav><footer><span>Single-click expands folders</span><span>Double-click opens records</span></footer></aside></div>
}
