import { callMethod, fetchListPage, type FrappeRow, type ListFilter } from './frappe'
import type { PortalRole } from '../roles/admin/roleConfig'

export type ExplorerNodeKind = 'root' | 'group' | 'entity' | 'record'
export type ExplorerNode = { id: string; kind: ExplorerNodeKind; entity?: string; recordId?: string; label: string; metadata?: string; route?: string; createRoute?: string; expandable?: boolean; filters?: ListFilter[] }
export type DiscoveryResult = { id: string; group: 'Navigation' | 'Records' | 'Tree' | 'Actions' | 'Help'; kind: string; title: string; detail: string; route: string; treePath?: string }

const roleGroups: Record<PortalRole, string[]> = {
  administrator: ['students','academics','registration','finance','results','transcripts'],
  registrar: ['students','academics','registration','results','transcripts'],
  'faculty-head': ['students','academics','registration','results','transcripts'],
  lecturer: ['students','registration','results'],
  finance: ['students','finance'],
  student: ['registration','finance','results','transcripts'],
  staff: [],
}

const groups: Record<string, ExplorerNode> = {
  students:{id:'group:students',kind:'group',label:'Students and cohorts',metadata:'Student records',route:'/students',expandable:true},
  academics:{id:'group:academics',kind:'group',label:'Academic structure',metadata:'Programmes and courses',route:'/academics',expandable:true},
  registration:{id:'group:registration',kind:'group',label:'Teaching and registration',metadata:'Offerings and enrolments',route:'/registration',expandable:true},
  finance:{id:'group:finance',kind:'group',label:'Finance',metadata:'Invoices and payments',route:'/finance',expandable:true},
  results:{id:'group:results',kind:'group',label:'Results',metadata:'Marks and publication',route:'/results',expandable:true},
  transcripts:{id:'group:transcripts',kind:'group',label:'Transcripts',metadata:'Issued academic records',route:'/transcripts',expandable:true},
}

const entityDefinitions: Record<string, {label:string;doctype:string;fields:string[];title:string;detail:string;route:string;createRoute?:string}> = {
  Student:{label:'Students',doctype:'Student',fields:['name','student_name','student_number','status'],title:'student_name',detail:'student_number',route:'/students',createRoute:'/students?create=student'},
  Cohort:{label:'Cohorts',doctype:'Student Cohort',fields:['name','cohort_name','cohort_code','academic_programme','status'],title:'cohort_name',detail:'academic_programme',route:'/students/cohorts',createRoute:'/students/cohorts?create=cohort'},
  Programme:{label:'Programmes',doctype:'Academic Programme',fields:['name','programme_name','programme_code','status'],title:'programme_name',detail:'programme_code',route:'/academics',createRoute:'/academics?create=programme'},
  Course:{label:'Courses',doctype:'Course',fields:['name','course_name','course_code','academic_unit','status'],title:'course_name',detail:'course_code',route:'/academics/courses',createRoute:'/academics/courses?create=course'},
  Offering:{label:'Course offerings',doctype:'Course Offering',fields:['name','course','academic_semester','student_cohort','status'],title:'course',detail:'academic_semester',route:'/registration/offerings',createRoute:'/registration/offerings?create=offering'},
  Enrolment:{label:'Programme enrolments',doctype:'Student Programme Enrolment',fields:['name','student','academic_programme','student_cohort','status'],title:'student',detail:'academic_programme',route:'/students/enrolments',createRoute:'/students/enrolments?create=enrolment'},
  Invoice:{label:'Student invoices',doctype:'Sales Invoice',fields:['name','student','customer','academic_semester','outstanding_amount','status'],title:'student',detail:'academic_semester',route:'/finance/invoices'},
  Result:{label:'Course results',doctype:'Student Course Result',fields:['name','student','course','academic_semester','grade','result_status'],title:'student',detail:'course',route:'/results'},
  Transcript:{label:'Transcripts',doctype:'Academic Transcript',fields:['name','student','academic_programme','status','verification_number'],title:'student',detail:'academic_programme',route:'/transcripts/register'},
}

const groupEntities: Record<string,string[]> = { students:['Cohort','Student'], academics:['Programme','Course'], registration:['Offering','Enrolment'], finance:['Invoice'], results:['Result'], transcripts:['Transcript'] }
const roleEntities: Record<PortalRole,string[]> = {
  administrator:Object.keys(entityDefinitions),
  registrar:['Student','Cohort','Programme','Course','Offering','Enrolment','Result','Transcript'],
  'faculty-head':[],
  lecturer:[],
  finance:['Student','Invoice'],
  student:[],
  staff:[],
}
export function explorerRoots(_role: PortalRole): ExplorerNode[] { return [{id:'university',kind:'root',label:'Ankole Western University',metadata:'University workspace',expandable:true}] }

type LecturerTreeData={offerings:FrappeRow[];registrations:FrappeRow[];students:FrappeRow[]}
let lecturerTreeRequest:Promise<LecturerTreeData>|null=null
function lecturerTreeData(){lecturerTreeRequest??=callMethod<LecturerTreeData>('ugandan_university_education.ugandan_university_education.api.get_lecturer_portal_data').catch(cause=>{lecturerTreeRequest=null;throw cause});return lecturerTreeRequest}

type StudentTreeData={student:FrappeRow;enrolments:FrappeRow[];semester_registrations:FrappeRow[];course_registrations:FrappeRow[];results:FrappeRow[];invoices:FrappeRow[];payments:FrappeRow[];transcripts:FrappeRow[];clearance:FrappeRow[]}
let studentTreeRequest:Promise<StudentTreeData>|null=null
function studentTreeData(){studentTreeRequest??=callMethod<StudentTreeData>('ugandan_university_education.ugandan_university_education.api.get_student_portal_data').catch(cause=>{studentTreeRequest=null;throw cause});return studentTreeRequest}

type FacultyTreeData={head_units:FrappeRow[];units:FrappeRow[];programmes:FrappeRow[];courses:FrappeRow[];curricula:FrappeRow[];enrolments:FrappeRow[];offerings:FrappeRow[];lecturers:FrappeRow[];results:FrappeRow[];approval_batches:FrappeRow[]}
let facultyTreeRequest:Promise<FacultyTreeData>|null=null
function facultyTreeData(){facultyTreeRequest??=callMethod<FacultyTreeData>('ugandan_university_education.ugandan_university_education.api.get_faculty_head_portal_data').catch(cause=>{facultyTreeRequest=null;throw cause});return facultyTreeRequest}

function semesterValue(row:FrappeRow){return String(row.academic_semester??row.academic_year??'Unassigned semester')}
function studentJourneyGroup(id:string,label:string,metadata:string,route:string):ExplorerNode{return{id,kind:'group',label,metadata,route,expandable:true}}

export async function loadExplorerChildren(node: ExplorerNode, role: PortalRole, signal?: AbortSignal): Promise<ExplorerNode[]> {
  if (node.kind === 'root' && role === 'lecturer') return [{id:'lecturer:offerings',kind:'group',label:'My Offerings',metadata:'Assigned teaching load',route:'/lecturer/offerings',expandable:true}]
  if (node.kind === 'root' && role === 'student') return [studentJourneyGroup('student:programmes','My Programme','My personal academic journey','/student/registration')]
  if (node.kind === 'root' && role === 'faculty-head') return [studentJourneyGroup('faculty:units','My Assigned Faculties & Units','Server-authorized leadership scope','/faculty/profile')]
  if (node.kind === 'root') return (roleGroups[role]??[]).map(id=>groups[id])
  if (role === 'lecturer' && node.id === 'lecturer:offerings') { const data=await lecturerTreeData(); return data.offerings.map(row=>({id:`lecturer:offering:${String(row.name)}`,kind:'record',entity:'Offering',recordId:String(row.name),label:String(row.course_name??row.course_code??row.course??row.name),metadata:`${String(row.academic_semester??'Semester')} · ${String(row.status??'Assigned')}`,route:`/lecturer/offerings?offering=${encodeURIComponent(String(row.name))}`,expandable:true})) }
  if (role === 'lecturer' && node.kind === 'record' && node.entity === 'Offering') { const data=await lecturerTreeData(); return data.registrations.filter(row=>String(row.course_offering)===String(node.recordId)).map(row=>({id:`lecturer:registration:${String(row.name)}`,kind:'record',entity:'Registration',recordId:String(row.name),label:String(row.student_name??row.student),metadata:`${String(row.student_number??row.student)} · ${String(row.status??'Registered')}`,route:`/lecturer/students?offering=${encodeURIComponent(String(node.recordId))}`,expandable:true})) }
  if (role === 'lecturer' && node.kind === 'record' && node.entity === 'Registration') { const data=await lecturerTreeData(),registration=data.registrations.find(row=>String(row.name)===String(node.recordId)),student=data.students.find(row=>String(row.name)===String(registration?.student)); return student?[{id:`lecturer:student:${String(student.name)}`,kind:'record',entity:'Student',recordId:String(student.name),label:String(student.student_name??student.name),metadata:String(student.student_number??student.status??''),route:'/lecturer/students',expandable:false}]:[] }
  if (role === 'student' && node.id === 'student:programmes') { const data=await studentTreeData(); return data.enrolments.map(row=>({id:`student:programme:${String(row.name)}`,kind:'record',entity:'PersonalProgramme',recordId:String(row.name),label:String(row.academic_programme??row.programme_name??'My Programme'),metadata:String(row.status??'Enrolled'),route:'/student/registration',expandable:true})) }
  if (role === 'student' && node.entity === 'PersonalProgramme') { const data=await studentTreeData(),programme=data.enrolments.find(row=>String(row.name)===String(node.recordId)); return data.semester_registrations.filter(row=>!programme?.academic_programme||!row.academic_programme||String(row.academic_programme)===String(programme.academic_programme)).map(row=>({id:`student:semester:${String(row.name)}`,kind:'record',entity:'PersonalSemester',recordId:String(row.name),label:semesterValue(row),metadata:String(row.status??'Registered'),route:`/student/registration?semester=${encodeURIComponent(semesterValue(row))}`,expandable:true})) }
  if (role === 'student' && node.entity === 'PersonalSemester') { const data=await studentTreeData(),semester=data.semester_registrations.find(row=>String(row.name)===String(node.recordId)),value=semesterValue(semester??{}); return [studentJourneyGroup(`student:courses:${value}`,'My Courses',value,`/student/courses?semester=${encodeURIComponent(value)}`),studentJourneyGroup(`student:results:${value}`,'My Results',value,`/student/results?semester=${encodeURIComponent(value)}`),studentJourneyGroup(`student:finance:${value}`,'My Finance',value,`/student/finance?semester=${encodeURIComponent(value)}`),studentJourneyGroup(`student:documents:${value}`,'My Documents',value,`/student/transcript?semester=${encodeURIComponent(value)}`)] }
  if (role === 'student' && node.id.startsWith('student:courses:')) { const data=await studentTreeData(),value=node.id.slice('student:courses:'.length); return data.course_registrations.filter(row=>semesterValue(row)===value).map(row=>({id:`student:course:${String(row.name)}`,kind:'record',entity:'PersonalCourse',recordId:String(row.name),label:String(row.course_name??row.course??row.course_code??row.name),metadata:String(row.status??'Registered'),route:`/student/courses?semester=${encodeURIComponent(value)}`,expandable:false})) }
  if (role === 'student' && node.id.startsWith('student:results:')) { const data=await studentTreeData(),value=node.id.slice('student:results:'.length); return data.results.filter(row=>semesterValue(row)===value).map(row=>({id:`student:result:${String(row.name)}`,kind:'record',entity:'PersonalResult',recordId:String(row.name),label:String(row.course_name??row.course??row.name),metadata:[row.grade,row.result_status??row.status].filter(Boolean).join(' · '),route:`/student/results?semester=${encodeURIComponent(value)}`,expandable:false})) }
  if (role === 'student' && node.id.startsWith('student:finance:')) { const data=await studentTreeData(),value=node.id.slice('student:finance:'.length),invoices=data.invoices.filter(row=>semesterValue(row)===value).map(row=>({id:`student:invoice:${String(row.name)}`,kind:'record' as const,entity:'PersonalInvoice',recordId:String(row.name),label:`Invoice ${String(row.name)}`,metadata:String(row.status??'Invoice'),route:`/student/finance?semester=${encodeURIComponent(value)}`,expandable:false})),payments=data.payments.filter(row=>semesterValue(row)===value).map(row=>({id:`student:payment:${String(row.name)}`,kind:'record' as const,entity:'PersonalPayment',recordId:String(row.name),label:`Receipt ${String(row.name)}`,metadata:String(row.status??'Payment'),route:`/student/finance?semester=${encodeURIComponent(value)}`,expandable:false})); return [...invoices,...payments] }
  if (role === 'student' && node.id.startsWith('student:documents:')) { const data=await studentTreeData(),value=node.id.slice('student:documents:'.length),transcripts=data.transcripts.map(row=>({id:`student:transcript:${String(row.name)}`,kind:'record' as const,entity:'PersonalTranscript',recordId:String(row.name),label:String(row.transcript_type??'Academic Transcript'),metadata:String(row.status??'Pending'),route:'/student/transcript',expandable:false})),clearance=data.clearance.filter(row=>semesterValue(row)===value||semesterValue(row)==='Unassigned semester').map(row=>({id:`student:clearance:${String(row.name)}`,kind:'record' as const,entity:'PersonalClearance',recordId:String(row.name),label:`${String(row.clearance_type??'Student')} Clearance`,metadata:String(row.status??'Pending'),route:'/student/clearance',expandable:false})); return [...transcripts,...clearance] }
  if (role === 'faculty-head' && node.id === 'faculty:units') { const data=await facultyTreeData(); return data.head_units.map(row=>({id:`faculty:unit:${String(row.name)}`,kind:'record',entity:'FacultyUnit',recordId:String(row.name),label:String(row.unit_name??row.name),metadata:String(row.unit_type??'Academic unit'),route:'/faculty/profile',expandable:true})) }
  if (role === 'faculty-head' && node.entity === 'FacultyUnit') { const data=await facultyTreeData(),children=data.units.filter(row=>String(row.parent_academic_unit)===String(node.recordId)).map(row=>({id:`faculty:unit:${String(row.name)}`,kind:'record' as const,entity:'FacultyUnit',recordId:String(row.name),label:String(row.unit_name??row.name),metadata:String(row.unit_type??'Academic unit'),route:'/faculty/profile',expandable:true})),programmes=data.programmes.filter(row=>String(row.academic_unit)===String(node.recordId)).map(row=>({id:`faculty:programme:${String(row.name)}`,kind:'record' as const,entity:'FacultyProgramme',recordId:String(row.name),label:String(row.programme_name??row.name),metadata:String(row.programme_code??row.status??''),route:`/faculty/programmes?programme=${encodeURIComponent(String(row.name))}`,expandable:true})); return [...children,...programmes] }
  if (role === 'faculty-head' && node.entity === 'FacultyProgramme') { const value=String(node.recordId); return [studentJourneyGroup(`faculty:offerings:${value}`,'Course Offerings','Teaching delivery','/faculty/offerings'),studentJourneyGroup(`faculty:lecturers:${value}`,'Lecturers','Teaching assignments','/faculty/lecturers'),studentJourneyGroup(`faculty:students:${value}`,'Students','Programme enrolments','/faculty/students'),studentJourneyGroup(`faculty:results:${value}`,'Results & Approvals','Academic decisions','/faculty/approvals')] }
  if (role === 'faculty-head' && node.id.startsWith('faculty:')) { const data=await facultyTreeData(),parts=node.id.split(':'),kind=parts[1],programme=parts.slice(2).join(':'),programmeRow=data.programmes.find(row=>String(row.name)===programme),curricula=new Set(data.curricula.filter(row=>String(row.academic_programme)===programme).map(row=>String(row.name))),courses=new Set(data.courses.filter(row=>String(row.academic_unit)===String(programmeRow?.academic_unit)).map(row=>String(row.name))),offerings=data.offerings.filter(row=>curricula.has(String(row.programme_curriculum))||courses.has(String(row.course))),offeringNames=new Set(offerings.map(row=>String(row.name))); if(kind==='offerings')return offerings.map(row=>({id:`faculty:offering:${String(row.name)}`,kind:'record',entity:'FacultyOffering',recordId:String(row.name),label:String(row.course_name??row.course_code??row.course),metadata:`${semesterValue(row)} · ${String(row.status??'')}`,route:`/faculty/offerings?offering=${encodeURIComponent(String(row.name))}`,expandable:false})); if(kind==='lecturers')return data.lecturers.filter(row=>(row.assignments as FrappeRow[]|undefined)?.some(item=>offeringNames.has(String(item.parent)))).map(row=>({id:`faculty:lecturer:${String(row.name)}`,kind:'record',entity:'FacultyLecturer',recordId:String(row.name),label:String(row.full_name??row.name),metadata:String(row.member_number??row.status??''),route:'/faculty/lecturers',expandable:false})); if(kind==='students')return data.enrolments.filter(row=>String(row.academic_programme)===programme).map(row=>({id:`faculty:student:${String(row.student)}`,kind:'record',entity:'FacultyStudent',recordId:String(row.student),label:String(row.student_name??row.student),metadata:String(row.student_number??row.status??''),route:'/faculty/students',expandable:false})); if(kind==='results'){const batches=data.approval_batches.filter(row=>offeringNames.has(String(row.course_offering))).map(row=>({id:`faculty:batch:${String(row.name)}`,kind:'record' as const,entity:'FacultyApprovalBatch',recordId:String(row.name),label:String(row.name),metadata:`${String(row.status??'')} · ${semesterValue(row)}`,route:`/faculty/approvals?batch=${encodeURIComponent(String(row.name))}`,expandable:false}));return batches} }
  if (node.kind === 'group') return (groupEntities[node.id.replace('group:','')]??[]).filter(entity=>roleEntities[role].includes(entity)).map(entity => { const definition=entityDefinitions[entity]; return {id:`entity:${entity}`,kind:'entity',entity,label:definition.label,metadata:definition.doctype,route:definition.route,createRoute:definition.createRoute,expandable:true} })
  if (node.kind === 'record' && node.entity === 'Cohort') { const definition=entityDefinitions.Enrolment; const result=await fetchListPage(definition.doctype,definition.fields,{pageSize:25,filters:[{field:'student_cohort',operator:'=',value:String(node.recordId)}],sortField:'modified'},signal); return result.rows.map(row=>recordNode('Enrolment',row)) }
  if (node.kind !== 'entity' || !node.entity || !entityDefinitions[node.entity] || !roleEntities[role].includes(node.entity)) return []
  const definition=entityDefinitions[node.entity], result=await fetchListPage(definition.doctype,definition.fields,{pageSize:25,filters:node.filters,sortField:'modified'},signal)
  return result.rows.map(row=>recordNode(node.entity!,row))
}

function recordNode(entity:string,row:FrappeRow):ExplorerNode { const definition=entityDefinitions[entity], recordId=String(row.name??''); return {id:`record:${entity}:${recordId}`,kind:'record',entity,recordId,label:String(row[definition.title]??recordId),metadata:[row[definition.detail],row.status??row.result_status].filter(Boolean).join(' · '),route:entity==='Student'?`/students/profile/${encodeURIComponent(recordId)}`:`${definition.route}?q=${encodeURIComponent(recordId)}&record=${encodeURIComponent(recordId)}&tree=${encodeURIComponent(`university/${entity}/${recordId}`)}`,expandable:entity==='Cohort'} }

const searchDefinitions = ['Student','Cohort','Programme','Course','Offering','Invoice','Result','Transcript']
export async function searchStudentJourney(query:string):Promise<DiscoveryResult[]>{
  const needle=query.toLowerCase(),data=await studentTreeData(),matches=(row:FrappeRow)=>Object.values(row).some(value=>String(value??'').toLowerCase().includes(needle))
  const pages=[['Overview','My academic journey','/student/dashboard'],['Profile','My student identity and contacts','/student/profile'],['Registration','My programme and semester registration','/student/registration'],['Courses','My registered courses','/student/courses'],['Timetable','My class schedule','/student/timetable'],['Attendance','My attendance history','/student/attendance'],['Finance','My invoices and receipts','/student/finance'],['Results','My published course results','/student/results'],['Transcript','My issued academic transcripts','/student/transcript'],['Clearance','My university clearance status','/student/clearance']]
  const navigation=pages.filter(([title,detail])=>`${title} ${detail}`.toLowerCase().includes(needle)).map(([title,detail,route],index)=>({id:`student:nav:${index}`,group:'Navigation' as const,kind:'Student page',title,detail,route}))
  const sources:Array<[string,FrappeRow[],string,(row:FrappeRow)=>string]>=[['Course',data.course_registrations,'/student/courses',row=>String(row.course_name??row.course??row.name)],['Result',data.results,'/student/results',row=>String(row.course_name??row.course??row.name)],['Invoice',data.invoices,'/student/finance',row=>`Invoice ${String(row.name)}`],['Receipt',data.payments,'/student/finance',row=>`Receipt ${String(row.name)}`],['Transcript',data.transcripts,'/student/transcript',row=>`${String(row.transcript_type??'Academic')} transcript`],['Clearance',data.clearance,'/student/clearance',row=>`${String(row.clearance_type??'Student')} clearance`]]
  const records=sources.flatMap(([kind,rows,route,label])=>rows.filter(matches).slice(0,4).map(row=>({id:`student:${kind}:${String(row.name)}`,group:'Records' as const,kind,title:label(row),detail:[semesterValue(row),row.status??row.result_status].filter(Boolean).join(' · '),route:`${route}?record=${encodeURIComponent(String(row.name))}`})))
  const tree=records.slice(0,6).map(record=>({...record,id:`tree:${record.id}`,group:'Tree' as const,detail:`Open in My Programme hierarchy · ${record.detail}`,treePath:`university/student/${record.kind}/${record.id}`}))
  return[...navigation,...records,...tree].slice(0,30)
}
export async function searchFacultyScope(query:string):Promise<DiscoveryResult[]>{
  const needle=query.toLowerCase(),data=await facultyTreeData(),matches=(row:FrappeRow)=>Object.values(row).some(value=>String(value??'').toLowerCase().includes(needle))
  const pages=[['Programmes','Scoped academic programmes','/faculty/programmes'],['Offerings','Faculty teaching delivery','/faculty/offerings'],['Lecturers','Assigned teaching staff','/faculty/lecturers'],['Students','Faculty programme enrolments','/faculty/students'],['Workload','Programme and lecturer workload','/faculty/workload'],['Approvals','Submitted result batches','/faculty/approvals'],['Reviews','Result review queue','/faculty/reviews'],['Transcripts','Faculty transcript readiness','/faculty/transcripts']]
  const navigation=pages.filter(([title,detail])=>`${title} ${detail}`.toLowerCase().includes(needle)).map(([title,detail,route],index)=>({id:`faculty:nav:${index}`,group:'Navigation' as const,kind:'Faculty page',title,detail,route}))
  const sources:Array<[string,FrappeRow[],string,(row:FrappeRow)=>string]>=[['Programme',data.programmes,'/faculty/programmes',row=>String(row.programme_name??row.name)],['Offering',data.offerings,'/faculty/offerings',row=>String(row.course_name??row.course_code??row.course)],['Lecturer',data.lecturers,'/faculty/lecturers',row=>String(row.full_name??row.name)],['Approval batch',data.approval_batches,'/faculty/approvals',row=>String(row.name)]]
  const records=sources.flatMap(([kind,rows,route,label])=>rows.filter(matches).slice(0,5).map(row=>({id:`faculty:${kind}:${String(row.name)}`,group:'Records' as const,kind,title:label(row),detail:[row.academic_semester,row.status,row.programme_code??row.member_number].filter(Boolean).join(' · '),route:`${route}?record=${encodeURIComponent(String(row.name))}`})))
  return[...navigation,...records,...records.slice(0,6).map(record=>({...record,id:`tree:${record.id}`,group:'Tree' as const,detail:`Open in assigned faculty hierarchy · ${record.detail}`,treePath:`university/faculty/${record.kind}/${record.id}`}))].slice(0,30)
}
export async function searchUniversity(query:string, role:PortalRole, signal?:AbortSignal):Promise<DiscoveryResult[]> { const allowedGroups=new Set(roleGroups[role]??[]), allowed=searchDefinitions.filter(entity=>roleEntities[role].includes(entity)&&Object.entries(groupEntities).some(([group,entities])=>allowedGroups.has(group)&&entities.includes(entity))); const settled=await Promise.allSettled(allowed.map(async entity=>{const definition=entityDefinitions[entity];const page=await fetchListPage(definition.doctype,definition.fields,{search:query,searchFields:definition.fields.slice(0,4),pageSize:25,sortField:'modified'},signal);return page.rows.slice(0,5).map(row=>{const node=recordNode(entity,row);return{id:node.id,group:'Records' as const,kind:entity,title:node.label,detail:node.metadata??definition.label,route:node.route??definition.route,treePath:`university/${entity}/${node.recordId}`}})})); const records=settled.flatMap(result=>result.status==='fulfilled'?result.value:[]); const tree=records.slice(0,5).map(record=>({...record,id:`tree:${record.id}`,group:'Tree' as const,detail:`Open in University hierarchy · ${record.detail}`})); const navigation=(roleGroups[role]??[]).map(id=>groups[id]).filter(node=>`${node.label} ${node.metadata}`.toLowerCase().includes(query.toLowerCase())).map(node=>({id:`nav:${node.id}`,group:'Navigation' as const,kind:'Section',title:node.label,detail:node.metadata??'',route:node.route??'/dashboard'})); const actions=(role==='administrator'&&'add new student'.includes(query.toLowerCase()))?[{id:'action:add-student',group:'Actions' as const,kind:'Action',title:'Add a student',detail:'Open the native student workspace',route:'/students?create=student'}]:[]; const help='filters export import pagination explorer'.includes(query.toLowerCase())?[{id:'help:workbench',group:'Help' as const,kind:'Help',title:'Using the Data Workbench',detail:'Search, filter, select, import and export records',route:'/students?help=workbench'}]:[]; return [...navigation,...records,...tree,...actions,...help].slice(0,30) }

export function auditDiscovery(event:'search'|'tree_open'|'tree_select'|'search_select',metadata:Record<string,unknown>={}) { const safe={event,queryLength:Number(metadata.queryLength??0),kind:String(metadata.kind??''),route:String(metadata.route??'').split('?')[0],at:new Date().toISOString()}; try{const key='awu-discovery-audit';const entries=JSON.parse(localStorage.getItem(key)??'[]');localStorage.setItem(key,JSON.stringify([...entries.slice(-99),safe]))}catch{} const match=window.location.pathname.match(/\/app-api\/apps\/([^/]+)\//);if(match)navigator.sendBeacon?.(`/app-api/apps/${encodeURIComponent(match[1])}/university/audit`,new Blob([JSON.stringify(safe)],{type:'application/json'})) }
