import { CalendarDays, CheckCircle2, ChevronDown, FileSpreadsheet, Layers3 } from 'lucide-react'
import { ugx } from '../../../../api/frappe'
import { FinanceIntro, FinanceMetric, FinancePageState, FinanceStatus, financeDate } from '../FinanceCommon'

export function FinanceStructuresPage() {
  return <FinancePageState>{data => {
    const active = data.fee_structures.filter(row => String(row.status) === 'Active'), total = active.reduce((sum, row) => sum + Number(row.total_amount ?? 0), 0)
    return <section className="student-portal-page"><FinanceIntro icon={FileSpreadsheet} eyebrow="APPROVED FEE SCHEDULES" title="University Fee Structures" description="Review submitted programme charges, mandatory components and effective periods before using them for student billing."/>
      <section className="student-portal-metrics"><FinanceMetric icon={FileSpreadsheet} label="Fee structures" value={data.fee_structures.length} detail="all versions" tone="blue"/><FinanceMetric icon={CheckCircle2} label="Active" value={active.length} detail="available for billing"/><FinanceMetric icon={Layers3} label="Active value" value={ugx(total)} detail="combined structure totals" tone="violet"/><FinanceMetric icon={CalendarDays} label="Semesters covered" value={new Set(active.map(row => row.academic_semester).filter(Boolean)).size} detail="active billing periods" tone="gold"/></section>
      <div className="student-accordion-list">{data.fee_structures.map((structure, index) => { const lines = (structure.fee_lines as Record<string, unknown>[] | undefined) ?? []; return <details className="student-accordion card finance-structure-accordion" key={String(structure.name)} open={index === 0}><summary><span><ChevronDown size={19}/><b>{String(structure.structure_name ?? structure.name)}</b><small>{String(structure.academic_programme)} · {String(structure.academic_semester ?? structure.academic_year)} · {ugx(structure.total_amount)}</small></span><FinanceStatus tone={String(structure.status) === 'Active' ? 'green' : Number(structure.docstatus) === 0 ? 'gold' : 'danger'}>{String(structure.status)}</FinanceStatus></summary><div className="student-accordion-body"><section className="semester-finance-strip"><div><small>Programme</small><strong>{String(structure.academic_programme)}</strong></div><div><small>Academic period</small><strong>{String(structure.academic_semester ?? structure.academic_year)}</strong></div><div><small>Effective period</small><strong>{financeDate(structure.effective_from)} – {financeDate(structure.effective_to)}</strong></div><div><small>Total assessed</small><strong>{ugx(structure.total_amount)}</strong></div></section><h4>Fee components</h4><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Description</th><th>Quantity</th><th>Rate</th><th>Line Total</th><th>Requirement</th></tr></thead><tbody>{lines.length ? lines.map((line, lineIndex) => <tr key={`${structure.name}-${lineIndex}`}><td><strong>{String(line.item)}</strong></td><td>{String(line.description ?? 'University fee component')}</td><td>{Number(line.quantity ?? 0)}</td><td>{ugx(line.rate)}</td><td><strong>{ugx(Number(line.quantity ?? 0) * Number(line.rate ?? 0))}</strong></td><td><FinanceStatus tone={line.mandatory ? 'blue' : 'gold'}>{line.mandatory ? 'Mandatory' : 'Optional'}</FinanceStatus></td></tr>) : <tr><td colSpan={6} className="data-table-empty">No fee components are attached to this structure.</td></tr>}</tbody></table></div></div></details> })}</div>
    </section>
  }}</FinancePageState>
}
