import { BookOpenCheck, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, GraduationCap, MapPin } from 'lucide-react'
import { StudentMetric, StudentPageState, StudentStatus, formatStudentDate } from '../StudentCommon'

export type StudentAcademicView='registration'|'courses'|'timetable'|'attendance'

export function StudentAcademicsPage({view}:{view:StudentAcademicView}){return <StudentPageState>{data=>{
  if(view==='registration') return <section className="student-portal-page"><Intro icon={GraduationCap} eyebrow="MY REGISTRATION" title="Semester Registration" description="Review your programme enrolment and every semester registration recorded by the university."/><section className="student-portal-metrics"><StudentMetric icon={GraduationCap} label="Programme enrolments" value={data.enrolments.length} detail="programme records"/><StudentMetric icon={CalendarDays} label="Registered semesters" value={data.semester_registrations.length} detail="semester activation records" tone="blue"/><StudentMetric icon={BookOpenCheck} label="Course registrations" value={data.course_registrations.length} detail="selected course offerings" tone="violet"/><StudentMetric icon={CheckCircle2} label="Active status" value={String(data.student.status??'—')} detail="student record status" tone="green"/></section><div className="student-accordion-list">{data.semester_registrations.map((row,index)=>{const courses=data.course_registrations.filter(course=>String(course.semester_registration)===String(row.name));return <details className="student-accordion card" key={String(row.name)} open={index===0}><summary><span><CalendarDays size={19}/><b>{String(row.academic_semester??row.name)}</b><small>{courses.length} registered courses</small></span><StudentStatus tone={String(row.status)==='Registered'?'green':'gold'}>{String(row.status??'Pending')}</StudentStatus></summary><div className="student-accordion-body"><dl className="student-definition-list inline"><div><dt>Registration date</dt><dd>{formatStudentDate(row.registration_date)}</dd></div><div><dt>Registration number</dt><dd>{String(row.name)}</dd></div><div><dt>Status</dt><dd>{String(row.status??'—')}</dd></div></dl>{courses.length?<CourseTable rows={courses}/>:<p className="student-empty-inline">No course registrations are linked to this semester.</p>}</div></details>})}</div></section>
  if(view==='courses') return <section className="student-portal-page"><Intro icon={BookOpenCheck} eyebrow="MY ACADEMIC LOAD" title="Registered Courses" description="Review course codes, credit units, semesters, attempts and registration status."/><article className="card student-table-card"><CourseTable rows={data.course_registrations}/></article></section>
  if(view==='timetable') return <section className="student-portal-page"><Intro icon={CalendarDays} eyebrow="MY CLASS SCHEDULE" title="Teaching Timetable" description="Published lectures, tutorials, practical sessions and examinations for your registered courses."/><div className="student-schedule-grid">{data.timetable.length?data.timetable.map(row=><article className="card schedule-card" key={String(row.name)}><header><span>{String(row.weekday??'Scheduled')}</span><StudentStatus tone="blue">{String(row.session_type??'Class')}</StudentStatus></header><h3>{String(row.course_name??row.course_code??row.course_offering)}</h3><p>{String(row.course_code??row.course_offering)}</p><div><span><Clock3 size={16}/>{String(row.start_time??'—')} – {String(row.end_time??'—')}</span><span><MapPin size={16}/>{String(row.venue??'Venue to be confirmed')}</span></div><small>{String(row.academic_semester??'')}</small></article>):<div className="student-state card"><CalendarDays size={30}/><h2>No published timetable yet</h2><p>Your timetable will appear here when the university publishes sessions for your registered offerings.</p></div>}</div></section>
  return <section className="student-portal-page"><Intro icon={ClipboardCheck} eyebrow="MY PARTICIPATION" title="Attendance Record" description="Review attendance captured for your registered classes and teaching sessions."/><article className="card student-table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Course Registration</th><th>Timetable Session</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{data.attendance.length?data.attendance.map(row=><tr key={String(row.name)}><td>{formatStudentDate(row.attendance_date)}</td><td><strong>{String(row.course_registration??'—')}</strong></td><td>{String(row.timetable_entry??'—')}</td><td><StudentStatus tone={String(row.status)==='Present'?'green':String(row.status)==='Late'?'gold':'danger'}>{String(row.status??'—')}</StudentStatus></td><td>{String(row.remarks??'—')}</td></tr>):<tr><td colSpan={5} className="data-table-empty">No attendance entries have been published.</td></tr>}</tbody></table></div></article></section>
 }}</StudentPageState>}

function Intro({icon:Icon,eyebrow,title,description}:{icon:any;eyebrow:string;title:string;description:string}){return <div className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h1><Icon size={28}/>{title}</h1><p>{description}</p></div></div>}
function CourseTable({rows}:{rows:Record<string,unknown>[]}){return <div className="table-wrap"><table className="data-table"><thead><tr><th>Course</th><th>Semester</th><th>Credit Units</th><th>Registration</th><th>Attempt</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={String(row.name)}><td><strong>{String(row.course_name??row.course??row.course_offering??'Course')}</strong><small>{String(row.course_code??row.course_offering??'')}</small></td><td>{String(row.academic_semester??'—')}</td><td>{String(row.credit_units??'—')}</td><td>{String(row.registration_type??'Normal')}</td><td>{String(row.attempt_number??1)}</td><td><StudentStatus tone={String(row.status)==='Registered'?'green':'gold'}>{String(row.status??'—')}</StudentStatus></td></tr>):<tr><td colSpan={6} className="data-table-empty">No registered courses are available.</td></tr>}</tbody></table></div>}
