import { ArrowRight, BadgeDollarSign, Banknote, CircleAlert, CircleDollarSign, FileSpreadsheet, HandCoins, ReceiptText, ShieldCheck, UsersRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { ugx } from '../../../../api/frappe'
import { FinanceMetric, FinancePageState, FinanceStatus } from '../FinanceCommon'

export function FinanceDashboardPage() {
  const navigate = useNavigate()
  return <FinancePageState>{data => {
    const submitted = data.invoices.filter(row => Number(row.docstatus) === 1)
    const assessed = submitted.reduce((sum, row) => sum + Number(row.grand_total ?? 0), 0)
    const outstanding = submitted.reduce((sum, row) => sum + Number(row.outstanding_amount ?? 0), 0)
    const received = data.payments.reduce((sum, row) => sum + Number(row.received_amount ?? row.paid_amount ?? 0), 0)
    const attention = submitted.filter(row => Number(row.outstanding_amount ?? 0) > 0).sort((a, b) => Number(b.outstanding_amount ?? 0) - Number(a.outstanding_amount ?? 0)).slice(0, 6)
    return <section className="student-portal-page">
      <section className="finance-welcome card"><div><span className="eyebrow">ANKOLE WESTERN UNIVERSITY FINANCE</span><h1>Good financial records. Clear student accounts.</h1><p>Control fee structures, semester billing, collections, sponsorships and financial clearance from one accountable workspace.</p><div className="hero-action-row"><button className="primary-button light" onClick={() => navigate('/finance/invoices')}><BadgeDollarSign size={16}/>Open billing desk</button><button className="secondary-button translucent" onClick={() => navigate('/finance/payments')}><ReceiptText size={16}/>Payment receipts</button></div></div><aside><span>Collection position</span><strong>{assessed ? `${Math.round((assessed - outstanding) / assessed * 100)}%` : 'No billing'}</strong><small>{ugx(outstanding)} currently outstanding</small><FinanceStatus tone={outstanding ? 'gold' : 'green'}>{outstanding ? 'Balances require follow-up' : 'Accounts settled'}</FinanceStatus></aside></section>
      <section className="student-portal-metrics"><FinanceMetric icon={FileSpreadsheet} label="Total assessed" value={ugx(assessed)} detail={`${submitted.length} submitted invoices`} tone="blue"/><FinanceMetric icon={Banknote} label="Payments received" value={ugx(received)} detail={`${data.payments.length} posted receipts`}/><FinanceMetric icon={CircleAlert} label="Balance to collect" value={ugx(outstanding)} detail={`${attention.length} highest balances shown`} tone={outstanding ? 'gold' : 'green'}/><FinanceMetric icon={UsersRound} label="Student accounts" value={data.students.length} detail="registered student records" tone="violet"/></section>
      <section className="student-dashboard-grid"><article className="card student-table-card"><div className="analysis-section-heading"><div><span className="eyebrow">COLLECTION PRIORITIES</span><h3>Accounts requiring attention</h3></div><CircleDollarSign size={22}/></div><div className="finance-priority-list">{attention.length ? attention.map(row => <button key={String(row.name)} onClick={() => navigate(`/finance/analysis?student=${encodeURIComponent(String(row.student ?? ''))}`)}><span><strong>{String(row.student_name ?? row.student ?? row.customer)}</strong><small>{String(row.student_number ?? row.name)} · {String(row.academic_semester ?? 'Unassigned semester')}</small></span><b>{ugx(row.outstanding_amount)}</b><ArrowRight size={15}/></button>) : <p className="student-empty-inline">No submitted student balance requires attention.</p>}</div></article>
      <article className="card student-service-card"><div className="analysis-section-heading"><div><span className="eyebrow">FINANCE CONTROL QUEUES</span><h3>Today’s operational desk</h3></div><ShieldCheck size={22}/></div><div className="student-service-list"><button onClick={() => navigate('/finance/structures')}><FileSpreadsheet size={18}/><span><strong>{data.fee_structures.filter(row => String(row.status) === 'Active').length} active fee structures</strong><small>Review programme and semester charges</small></span></button><button onClick={() => navigate('/finance/sponsorships')}><HandCoins size={18}/><span><strong>{data.sponsorships.filter(row => ['Draft', 'Approved'].includes(String(row.status))).length} sponsorship decisions</strong><small>Approve or activate funding awards</small></span></button><button onClick={() => navigate('/finance/clearance')}><ShieldCheck size={18}/><span><strong>{data.clearance.filter(row => String(row.financial_status) !== 'Cleared').length} clearance checks</strong><small>Refresh outstanding account positions</small></span></button></div></article></section>
    </section>
  }}</FinancePageState>
}
