import { CheckCircle2, CircleAlert, GraduationCap, RefreshCw, Search, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { callMethod, ugx } from '../../../../api/frappe'
import { useFinancePortal } from '../../financePortal'
import { FinanceIntro, FinanceMetric, FinancePageState, FinanceStatus, financeDate } from '../FinanceCommon'

const method = 'ugandan_university_education.ugandan_university_education.api.review_financial_clearance'
export function FinanceClearancePage() {
  const { refresh } = useFinancePortal(), [query, setQuery] = useState(''), [busy, setBusy] = useState(''), [message, setMessage] = useState('')
  return <FinancePageState>{data => {
    const rows = data.clearance.filter(row => !query || JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))
    const balanceFor = (student: unknown) => data.invoices.filter(row => Number(row.docstatus) === 1 && String(row.student) === String(student)).reduce((sum, row) => sum + Number(row.outstanding_amount ?? 0), 0)
    async function review(name: string) { setBusy(name); setMessage(''); try { const result = await callMethod<{ financial_status: string; outstanding_amount: number }>(method, { clearance_name: name }); setMessage(`${name}: ${result.financial_status}, ${ugx(result.outstanding_amount)} outstanding.`); refresh() } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'The financial clearance could not be reviewed.') } finally { setBusy('') } }
    return <section className="student-portal-page"><FinanceIntro icon={ShieldCheck} eyebrow="FINANCIAL CLEARANCE CONTROL" title="Student Financial Clearance" description="Recalculate submitted invoice balances and certify the financial portion of registration, examination, withdrawal and graduation clearance."/>
      <section className="student-portal-metrics"><FinanceMetric icon={ShieldCheck} label="Clearance cases" value={data.clearance.length} detail="all finance checks" tone="blue"/><FinanceMetric icon={CheckCircle2} label="Financially cleared" value={data.clearance.filter(row => String(row.financial_status) === 'Cleared').length} detail="zero submitted balance"/><FinanceMetric icon={CircleAlert} label="Outstanding" value={data.clearance.filter(row => String(row.financial_status) === 'Outstanding').length} detail="payment required" tone="gold"/><FinanceMetric icon={GraduationCap} label="Graduation checks" value={data.clearance.filter(row => String(row.clearance_type) === 'Graduation').length} detail="final account reviews" tone="violet"/></section>
      {message ? <p className={message.includes('outstanding.') ? 'form-message success' : 'form-message'}>{message}</p> : null}
      <article className="card student-table-card"><div className="receipt-selection-toolbar"><label className="search-input"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search student, semester, clearance type or status"/></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Student</th><th>Clearance Request</th><th>Current Balance</th><th>Finance Status</th><th>Academic Status</th><th>Overall Status</th><th>Last Cleared</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map(row => { const balance = balanceFor(row.student); return <tr key={String(row.name)}><td><strong>{String(row.student_name ?? row.student)}</strong><small>{String(row.student_number ?? row.student)}</small></td><td>{String(row.clearance_type)}<small>{String(row.academic_semester ?? row.name)}</small></td><td><strong>{ugx(balance)}</strong></td><td><FinanceStatus tone={String(row.financial_status) === 'Cleared' ? 'green' : String(row.financial_status) === 'Outstanding' ? 'danger' : 'gold'}>{String(row.financial_status)}</FinanceStatus></td><td><FinanceStatus tone={String(row.academic_status) === 'Cleared' ? 'green' : 'gold'}>{String(row.academic_status)}</FinanceStatus></td><td>{String(row.status)}</td><td>{financeDate(row.cleared_on)}</td><td><button className="secondary-button compact" disabled={busy === String(row.name)} onClick={() => review(String(row.name))}><RefreshCw size={14}/>{busy === String(row.name) ? 'Checking…' : 'Refresh balance'}</button></td></tr> }) : <tr><td colSpan={8} className="data-table-empty">No clearance case matches this search.</td></tr>}</tbody></table></div></article>
    </section>
  }}</FinancePageState>
}
