import { CalendarDays, GraduationCap, IdCard, Mail, UserRound } from 'lucide-react'
import { StudentMetric, StudentPageState, formatStudentDate } from '../StudentCommon'

export function StudentProfilePage(){return <StudentPageState>{data=>{const student=data.student,enrolment=data.enrolments.find(row=>String(row.status)==='Active')??data.enrolments[0],name=String(student.student_name??student.name);return <section className="student-portal-page">
  <div className="page-intro"><div><span className="eyebrow">MY STUDENT RECORD</span><h1><UserRound size={28}/>Personal Profile</h1><p>Review the identity and programme information held on your official university record.</p></div></div>
  <section className="student-profile-banner card"><div className="profile-avatar profile-avatar-large">{name.split(/\s+/).slice(0,2).map(word=>word[0]).join('')}</div><div><span className="eyebrow">REGISTERED STUDENT</span><h2>{name}</h2><p>{String(student.student_number??student.name)} · {String(student.status??'Active')}</p></div></section>
  <section className="student-portal-metrics"><StudentMetric icon={IdCard} label="Student number" value={String(student.student_number??student.name)} detail="official registration identifier"/><StudentMetric icon={GraduationCap} label="Programme" value={String(enrolment?.academic_programme??'—')} detail="current academic programme" tone="violet"/><StudentMetric icon={CalendarDays} label="Admission year" value={String(enrolment?.academic_year??'—')} detail={formatStudentDate(enrolment?.admission_date)} tone="blue"/><StudentMetric icon={Mail} label="University email" value={String(student.student_email_id??'—')} detail="portal account email" tone="gold"/></section>
  <section className="student-profile-grid"><article className="card profile-panel"><div className="profile-panel-heading"><div><span className="eyebrow">PERSONAL INFORMATION</span><h2>Student identity</h2></div></div><div className="profile-details"><Detail label="Full name" value={name}/><Detail label="Gender" value={student.gender}/><Detail label="Date of birth" value={formatStudentDate(student.date_of_birth)}/><Detail label="Nationality" value={student.nationality}/><Detail label="Email" value={student.student_email_id}/><Detail label="Record status" value={student.status}/></div></article><article className="card profile-panel"><div className="profile-panel-heading"><div><span className="eyebrow">PROGRAMME PLACEMENT</span><h2>Current enrolment</h2></div></div><div className="profile-details one-column"><Detail label="Academic programme" value={enrolment?.academic_programme}/><Detail label="Curriculum" value={enrolment?.programme_curriculum}/><Detail label="Student cohort" value={enrolment?.student_cohort}/><Detail label="Expected completion" value={formatStudentDate(enrolment?.expected_completion_date)}/></div></article></section>
 </section>}}</StudentPageState>}

function Detail({label,value}:{label:string;value:unknown}){return <div><small>{label}</small><strong>{String(value??'—')}</strong></div>}
