import { createContext,useContext,useEffect,useMemo,useState,type ReactNode } from 'react'
import { callMethod,type FrappeRow } from '../../api/frappe'
import { useUrlScope } from '../../hooks/useUrlScope'
export type FacultyPortalData={faculty_head:FrappeRow;head_units:FrappeRow[];units:FrappeRow[];programmes:FrappeRow[];courses:FrappeRow[];curricula:FrappeRow[];cohorts:FrappeRow[];students:FrappeRow[];enrolments:FrappeRow[];offerings:FrappeRow[];lecturers:FrappeRow[];assessments:FrappeRow[];results:FrappeRow[];approval_batches:FrappeRow[];review_requests:FrappeRow[];transcripts:FrappeRow[];clearance:FrappeRow[]}
export type FacultyScope={unit:string;programme:string;semester:string;status:string;search:string}
type State={data:FacultyPortalData|null;allData:FacultyPortalData|null;scope:FacultyScope;setScope:(patch:Partial<FacultyScope>)=>void;loading:boolean;error:string;refresh:()=>void}
const Context=createContext<State|null>(null),method='ugandan_university_education.ugandan_university_education.api.get_faculty_head_portal_data',initial:FacultyScope={unit:'',programme:'',semester:'',status:'',search:''}
function filter(data:FacultyPortalData,scope:FacultyScope):FacultyPortalData{
 const match=(row:FrappeRow)=>!scope.search||Object.values(row).some(value=>String(value??'').toLowerCase().includes(scope.search.toLowerCase())),status=(row:FrappeRow)=>!scope.status||String(row.status??row.result_status)===scope.status,semester=(row:FrappeRow)=>!scope.semester||String(row.academic_semester??row.academic_year)===scope.semester
 const programmeScope=data.programmes.filter(row=>(!scope.unit||String(row.academic_unit)===scope.unit)&&(!scope.programme||String(row.name)===scope.programme)),programmeNames=new Set(programmeScope.map(row=>String(row.name))),courseScope=data.courses.filter(row=>!scope.unit||String(row.academic_unit)===scope.unit),courseNames=new Set(courseScope.map(row=>String(row.name))),offeringScope=data.offerings.filter(row=>courseNames.has(String(row.course))&&semester(row)&&status(row)),offeringNames=new Set(offeringScope.map(row=>String(row.name))),enrolmentScope=data.enrolments.filter(row=>programmeNames.has(String(row.academic_programme))&&status(row)),studentNames=new Set(enrolmentScope.map(row=>String(row.student))),programmes=programmeScope.filter(match),courses=courseScope.filter(match),offerings=offeringScope.filter(match),enrolments=enrolmentScope.filter(match)
 return{...data,programmes,courses,curricula:data.curricula.filter(row=>programmeNames.has(String(row.academic_programme))&&match(row)),cohorts:data.cohorts.filter(row=>programmeNames.has(String(row.academic_programme))&&semester(row)&&status(row)&&match(row)),enrolments,students:data.students.filter(row=>studentNames.has(String(row.name))&&match(row)),offerings,lecturers:data.lecturers.filter(row=>(row.assignments as FrappeRow[]|undefined)?.some(item=>offeringNames.has(String(item.parent)))&&match(row)),assessments:data.assessments.filter(row=>offeringNames.has(String(row.course_offering))&&status(row)&&match(row)),results:data.results.filter(row=>courseNames.has(String(row.course))&&semester(row)&&status(row)&&match(row)),approval_batches:data.approval_batches.filter(row=>offeringNames.has(String(row.course_offering))&&semester(row)&&status(row)&&match(row)),review_requests:data.review_requests.filter(row=>status(row)&&match(row)),transcripts:data.transcripts.filter(row=>programmeNames.has(String(row.academic_programme))&&status(row)&&match(row)),clearance:data.clearance.filter(row=>studentNames.has(String(row.student))&&semester(row)&&status(row)&&match(row))}
}
export function FacultyPortalProvider({children}:{children:ReactNode}){const[allData,setAllData]=useState<FacultyPortalData|null>(null),[scope,setScope]=useUrlScope(initial),[loading,setLoading]=useState(true),[error,setError]=useState('');function refresh(){setLoading(true);setError('');callMethod<FacultyPortalData>(method).then(setAllData).catch(cause=>setError(cause instanceof Error?cause.message:'Unable to load the faculty workspace.')).finally(()=>setLoading(false))}useEffect(refresh,[]);const data=useMemo(()=>allData?filter(allData,scope):null,[allData,scope]);return <Context.Provider value={{data,allData,scope,setScope,loading,error,refresh}}>{children}</Context.Provider>}
export function useFacultyPortal(){const value=useContext(Context);if(!value)throw new Error('useFacultyPortal must be used inside FacultyPortalProvider');return value}
