import { Award, BookOpenCheck, CalendarDays, ClipboardCheck, GraduationCap, UsersRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { LecturerMetric, LecturerPageState, LecturerStatus, offeringLabel } from '../LecturerCommon'

export function LecturerDashboardPage(){const navigate=useNavigate();return <LecturerPageState>{data=>{const open=data.offerings.filter(row=>String(row.status)==='Open'),pending=data.results.filter(row=>!Number(row.is_approved)),today=new Intl.DateTimeFormat('en-UG',{weekday:'long'}).format(new Date()),todaySessions=data.timetable.filter(row=>String(row.weekday)===today);return <section className="student-portal-page">
 <section className="lecturer-welcome card"><div><span className="eyebrow">WELCOME TO YOUR TEACHING DESK</span><h1>{String(data.lecturer.full_name??'Lecturer')}</h1><p>Manage assigned course offerings, class attendance, assessments, student marks and result submissions from one controlled workspace.</p><div className="hero-action-row"><button className="primary-button light" onClick={()=>navigate('/lecturer/attendance')}><ClipboardCheck size={16}/>Take attendance</button><button className="secondary-button translucent" onClick={()=>navigate('/lecturer/marks')}><GraduationCap size={16}/>Enter marks</button></div></div><aside><span>Lecturer number</span><strong>{String(data.lecturer.member_number??data.lecturer.name)}</strong><small>{data.offerings.length} assigned offering(s)</small><LecturerStatus>{String(data.lecturer.status??'Active')}</LecturerStatus></aside></section>
 <section className="student-portal-metrics"><LecturerMetric icon={BookOpenCheck} label="Assigned offerings" value={data.offerings.length} detail={`${open.length} currently open`} tone="blue"/><LecturerMetric icon={UsersRound} label="Registered students" value={data.students.length} detail={`${data.registrations.length} course registrations`}/><LecturerMetric icon={CalendarDays} label="Today's sessions" value={todaySessions.length} detail={today} tone="gold"/><LecturerMetric icon={Award} label="Results in progress" value={pending.length} detail={`${data.approval_batches.length} approval batches`} tone="violet"/></section>
 <section className="student-dashboard-grid"><article className="card student-service-card"><div className="section-heading"><div><span className="eyebrow">MY TEACHING LOAD</span><h3>Current course offerings</h3></div><BookOpenCheck size={22}/></div><div className="lecturer-offering-list">{data.offerings.slice(0,5).map(row=><button key={String(row.name)} onClick={()=>navigate('/lecturer/offerings')}><span><strong>{offeringLabel(row)}</strong><small>{String(row.course_name??row.course)} · {String(row.academic_semester??'Semester')}</small></span><LecturerStatus tone={String(row.status)==='Open'?'green':'gold'}>{String(row.status??'Planned')}</LecturerStatus></button>)}</div>{!data.offerings.length?<p className="student-empty-inline">No course offerings have been assigned to this lecturer account.</p>:null}</article>
 <article className="card student-service-card"><div className="section-heading"><div><span className="eyebrow">WORK QUEUE</span><h3>Teaching actions</h3></div><ClipboardCheck size={22}/></div><div className="student-service-list"><button onClick={()=>navigate('/lecturer/attendance')}><ClipboardCheck size={18}/><span><strong>Class attendance</strong><small>{data.attendance.length} entries recorded</small></span></button><button onClick={()=>navigate('/lecturer/marks')}><GraduationCap size={18}/><span><strong>Assessment marks</strong><small>{data.assessments.length} assessment components</small></span></button><button onClick={()=>navigate('/lecturer/reviews')}><Award size={18}/><span><strong>Review requests</strong><small>{data.review_requests.filter(row=>String(row.status)!=='Resolved').length} require attention</small></span></button></div></article></section>
 </section>}}</LecturerPageState>}
