import { Banknote, CheckCircle2, CircleAlert, CircleDollarSign, ReceiptText, Search } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ugx } from '../../../../api/frappe'
import { FinanceIntro, FinanceMetric, FinancePageState, FinanceStatus, financeDate } from '../FinanceCommon'

export function FinanceReconciliationPage() {
  const navigate = useNavigate(), [query, setQuery] = useState('')
  return <FinancePageState>{data => {
    const rows = data.payments.map(payment => { const allocations = (payment.allocations as Record<string, unknown>[] | undefined) ?? [], amount = Number(payment.received_amount ?? payment.paid_amount ?? 0), allocated = allocations.reduce((sum, row) => sum + Number(row.allocated_amount ?? 0), 0); return { payment, allocations, amount, allocated, unallocated: Math.max(0, amount - allocated) } }).filter(row => !query || JSON.stringify(row.payment).toLowerCase().includes(query.toLowerCase()))
    const received = rows.reduce((sum, row) => sum + row.amount, 0), allocated = rows.reduce((sum, row) => sum + row.allocated, 0), unallocated = rows.reduce((sum, row) => sum + row.unallocated, 0)
    return <section className="student-portal-page"><FinanceIntro icon={CircleDollarSign} eyebrow="COLLECTION RECONCILIATION" title="Payment Allocation Control" description="Verify posted receipts against student invoices, identify unapplied advances and trace each collection to its semester."/>
      <section className="student-portal-metrics"><FinanceMetric icon={Banknote} label="Receipts reviewed" value={rows.length} detail={ugx(received)} tone="blue"/><FinanceMetric icon={CheckCircle2} label="Allocated" value={ugx(allocated)} detail="matched to invoices"/><FinanceMetric icon={CircleAlert} label="Unallocated" value={ugx(unallocated)} detail="advance or unmatched value" tone={unallocated ? 'gold' : 'green'}/><FinanceMetric icon={ReceiptText} label="Allocation coverage" value={received ? `${Math.round(allocated / received * 100)}%` : '0%'} detail="of receipts applied" tone="violet"/></section>
      <article className="card student-table-card"><div className="receipt-selection-toolbar"><label className="search-input"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search payment, student, reference, mode or semester"/></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Payment</th><th>Student / Customer</th><th>Reference</th><th>Received</th><th>Allocated</th><th>Unallocated</th><th>Coverage</th><th>Actions</th></tr></thead><tbody>{rows.length ? rows.map(({ payment, allocations, amount, allocated, unallocated }) => <tr key={String(payment.name)}><td><strong>{String(payment.name)}</strong><small>{financeDate(payment.posting_date)} · {String(payment.mode_of_payment ?? 'Payment')}</small></td><td>{String(payment.student_name ?? payment.party_name ?? payment.party)}<small>{String(payment.student_number ?? payment.student ?? '')}</small></td><td>{String(payment.reference_no ?? 'No external reference')}<small>{allocations.map(row => row.academic_semester).filter(Boolean).join(', ') || 'Advance / unallocated'}</small></td><td><strong>{ugx(amount)}</strong></td><td>{ugx(allocated)}</td><td>{ugx(unallocated)}</td><td><FinanceStatus tone={unallocated === 0 ? 'green' : allocated ? 'gold' : 'danger'}>{unallocated === 0 ? 'Fully allocated' : allocated ? 'Part allocated' : 'Unallocated'}</FinanceStatus></td><td><button className="row-action-button" onClick={() => navigate(`/finance/payments?q=${encodeURIComponent(String(payment.name))}`)}><ReceiptText size={14}/>Receipt</button></td></tr>) : <tr><td colSpan={8} className="data-table-empty">No payment matches this search.</td></tr>}</tbody></table></div></article>
    </section>
  }}</FinancePageState>
}
