import type { ReactNode } from 'react'
import { RefreshCw } from 'lucide-react'
import { useLecturerPortal } from '../lecturerPortal'

export function LecturerPageState({children}:{children:(data:NonNullable<ReturnType<typeof useLecturerPortal>['data']>)=>ReactNode}){const{data,loading,error,refresh}=useLecturerPortal();if(loading)return <section className="student-state card"><span className="student-state-spinner"/><h2>Preparing your teaching workspace</h2><p>Please wait while assigned classes and assessment records are loaded.</p></section>;if(error||!data)return <section className="student-state card"><h2>We could not open your teaching records</h2><p>{error||'No lecturer information was returned.'}</p><button className="primary-button" onClick={refresh}><RefreshCw size={16}/>Try again</button></section>;return <>{children(data)}</>}
export function LecturerMetric({icon:Icon,label,value,detail,tone='green'}:{icon:any;label:string;value:string|number;detail:string;tone?:string}){return <article className="student-portal-metric card"><span className={`student-portal-metric-icon tone-${tone}`}><Icon size={20}/></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>}
export function LecturerIntro({icon:Icon,eyebrow,title,description,action}:{icon:any;eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h1><Icon size={28}/>{title}</h1><p>{description}</p></div>{action}</div>}
export function LecturerStatus({children,tone='green'}:{children:ReactNode;tone?:'green'|'gold'|'danger'|'blue'}){return <span className={`status-pill tone-${tone}`}>{children}</span>}
export function lecturerDate(value:unknown){if(!value)return '—';const text=String(value),date=new Date(text.length===10?`${text}T00:00:00`:text.replace(' ','T'));return Number.isNaN(date.getTime())?text:new Intl.DateTimeFormat('en-UG',{day:'2-digit',month:'short',year:'numeric'}).format(date)}
export function offeringLabel(row:Record<string,unknown>){return String(row.course_code??row.course_name??row.course??row.name??'Course offering')}
