import { BookOpenCheck, ChevronLeft, ChevronRight, Download, Eye, Search, X } from 'lucide-react'
import { useState } from 'react'
import { useLecturerPortal } from '../lecturerPortal'

function csv(name:string,headers:string[],rows:string[][]){const cell=(value:string)=>`"${value.replace(/"/g,'""')}"`,body=[headers,...rows].map(row=>row.map(cell).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([body],{type:'text/csv'})),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}

export function LecturerScopeBar(){const{allData,data,scope,setScope}=useLecturerPortal(),[drawer,setDrawer]=useState(false);if(!allData||!data)return null;const semesters=[...new Set(allData.offerings.map(row=>String(row.academic_semester??'')).filter(Boolean))],selected=allData.offerings.find(row=>String(row.name)===scope.offering),registrations=data.registrations,assessments=data.assessments;return <>
  <section className="lecturer-scope-bar card" aria-label="Lecturer workspace scope"><label><Search size={15}/><input value={scope.query} onChange={event=>setScope({query:event.target.value})} placeholder="Search assigned student, offering, course or session"/></label><select value={scope.semester} onChange={event=>setScope({semester:event.target.value,offering:''})}><option value="">All semesters</option>{semesters.map(value=><option key={value}>{value}</option>)}</select><select value={scope.offering} onChange={event=>setScope({offering:event.target.value})}><option value="">All assigned offerings</option>{allData.offerings.filter(row=>!scope.semester||String(row.academic_semester)===scope.semester).map(row=><option value={String(row.name)} key={String(row.name)}>{String(row.course_code??row.course)} · {String(row.academic_semester??'')}</option>)}</select><select value={scope.pageSize} onChange={event=>setScope({pageSize:Number(event.target.value) as 25|50|100|2000})}>{[25,50,100,2000].map(size=><option key={size} value={size}>{size} rows</option>)}</select><button disabled={!selected} onClick={()=>setDrawer(true)}><Eye size={15}/>Offering</button><button onClick={()=>csv('lecturer-class-list.csv',['Student','Number','Registration','Offering'],registrations.map(row=>[String(row.student_name??row.student),String(row.student_number??''),String(row.name),String(row.course_offering)]))}><Download size={15}/>Class list</button><button onClick={()=>csv('lecturer-marks-template.csv',['Course Assessment','Course Registration','Student','Mark','Comment'],assessments.flatMap(assessment=>registrations.filter(row=>String(row.course_offering)===String(assessment.course_offering)).map(row=>[String(assessment.name),String(row.name),String(row.student_name??row.student),'',''])))}><Download size={15}/>Marks template</button><span><button disabled={scope.page<=1} onClick={()=>setScope({page:scope.page-1})}><ChevronLeft size={14}/></button>Page {scope.page}<button onClick={()=>setScope({page:scope.page+1})}><ChevronRight size={14}/></button></span></section>
  {drawer&&selected?<div className="record-drawer-layer"><button className="record-drawer-backdrop" onClick={()=>setDrawer(false)}/><aside className="record-drawer lecturer-offering-drawer"><header><div><span className="eyebrow">ASSIGNED OFFERING</span><h2>{String(selected.course_code??selected.course)}</h2><p>{String(selected.academic_semester??'')}</p></div><button onClick={()=>setDrawer(false)}><X size={18}/></button></header><dl><div><dt>Course</dt><dd>{String(selected.course_name??selected.course)}</dd></div><div><dt>Cohort</dt><dd>{String(selected.student_cohort??'—')}</dd></div><div><dt>Teaching role</dt><dd>{String(selected.teaching_role??'Lecturer')}</dd></div><div><dt>Roster</dt><dd>{registrations.length} students</dd></div><div><dt>Timetable</dt><dd>{data.timetable.length} sessions</dd></div><div><dt>Attendance</dt><dd>{data.attendance.length} records</dd></div><div><dt>Assessments</dt><dd>{assessments.length} components</dd></div><div><dt>Marks/results</dt><dd>{data.results.length} records</dd></div><div><dt>Result batches</dt><dd>{data.approval_batches.length}</dd></div></dl></aside></div>:null}
  </>}
